### ISSUE TITLE
PKI-Tomcat logging breaks with permissions issues on rotation attempt

### ISSUE THREAD

**Issue by m3e-g** [freeipa/freeipa-container#593] opened 2024-02-27 10:32 UTC
I've noticed some time ago, that after each start of the container, new log files are created in the `/data/var/lib/pki/pki-tomcat/logs/acme` and `/data/var/lib/pki/pki-tomcat/logs/ca` and they are being written to until the 01:00 AM, when I see the following errors in the journal:

```
Feb 27 01:00:15 ipa.domain.com server[576]: java.util.logging.ErrorManager: 1: FileHandler is closed or not yet initialized, unable to log [2024-02-27 00:00:15 [pool-1-thread-1] SEVERE: Unable to run maintenance task: access denied ("java.io.FilePermission" "/data/var/lib/pki/pki-tomcat/logs/acme" "read")
Feb 27 01:00:15 ipa.domain.com server[576]: java.security.AccessControlException: access denied ("java.io.FilePermission" "/data/var/lib/pki/pki-tomcat/logs/acme" "read")
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.io.File.exists(File.java:829)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.io.File.mkdirs(File.java:1403)
Feb 27 01:00:15 ipa.domain.com server[576]:         at org.apache.juli.FileHandler.openWriter(FileHandler.java:491)
Feb 27 01:00:15 ipa.domain.com server[576]:         at org.apache.juli.FileHandler.publish(FileHandler.java:279)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.logging/java.util.logging.Logger.log(Logger.java:980)
Feb 27 01:00:15 ipa.domain.com server[576]:         at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
Feb 27 01:00:15 ipa.domain.com server[576]:         at org.slf4j.impl.JDK14LoggerAdapter.info(JDK14LoggerAdapter.java:277)
Feb 27 01:00:15 ipa.domain.com server[576]:         at org.dogtagpki.acme.scheduler.ACMEMaintenanceTask.run(ACMEMaintenanceTask.java:22)
Feb 27 01:00:15 ipa.domain.com server[576]:         at org.dogtagpki.acme.scheduler.ACMEScheduler$1.run(ACMEScheduler.java:59)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Feb 27 01:00:15 ipa.domain.com server[576]:         at java.base/java.lang.Thread.run(Thread.java:840)
Feb 27 01:00:15 ipa.domain.com server[576]: ]
Feb 27 01:00:17 ipa.domain.com server[576]: java.util.logging.ErrorManager: 1: FileHandler is closed or not yet initialized, unable to log [2024-02-27 00:00:17 [CertStatusUpdateTask] WARNING: CertStatusUpdateTask: access denied ("java.io.FilePermission" "/data/var/lib/pki/pki-tomcat/logs/ca" "read")
Feb 27 01:00:17 ipa.domain.com server[576]: java.security.AccessControlException: access denied ("java.io.FilePermission" "/data/var/lib/pki/pki-tomcat/logs/ca" "read")
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.io.File.exists(File.java:829)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.io.File.mkdirs(File.java:1403)
Feb 27 01:00:17 ipa.domain.com server[576]:         at org.apache.juli.FileHandler.openWriter(FileHandler.java:491)
Feb 27 01:00:17 ipa.domain.com server[576]:         at org.apache.juli.FileHandler.publish(FileHandler.java:279)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.logging/java.util.logging.Logger.log(Logger.java:980)
Feb 27 01:00:17 ipa.domain.com server[576]:         at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
Feb 27 01:00:17 ipa.domain.com server[576]:         at org.slf4j.impl.JDK14LoggerAdapter.info(JDK14LoggerAdapter.java:277)
Feb 27 01:00:17 ipa.domain.com server[576]:         at com.netscape.cmscore.dbs.CertStatusUpdateTask.updateCertStatus(CertStatusUpdateTask.java:215)
Feb 27 01:00:17 ipa.domain.com server[576]:         at com.netscape.cmscore.dbs.CertStatusUpdateTask.run(CertStatusUpdateTask.java:259)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Feb 27 01:00:17 ipa.domain.com server[576]:         at java.base/java.lang.Thread.run(Thread.java:840)
Feb 27 01:00:17 ipa.domain.com server[576]: ]
```

After those messages nothing else is being logged.

These folders (and files within) are owned by `pkiuser:pkiuser` and from what I can tell is it used to work correctly until I've messed something during my trials when looking for the fixes with the docker v25. I've messed up and didn't noticed that my logs were mounted in location without a backup. Files ownership were messed up and I had to fix it manually. Apparently I failed to do so.

Error comes from the tomcat server which also runs as the `pkiuser`, and the logs are written to until the first rotation attempt.

What ownership/permissions should those directories have?

Thanks

**Comment by abbra** [comment] 2024-02-27 10:49
It may well be a problem with Java access manager policies. The default policy PKI ships with is using `${catalina.base}` which infers `CATALINA_BASE` from `/etc/sysconfig/pki-tomcat` via `pki-tomcat` instance name:
```
# systemctl cat pki-tomcatd@.service
# /usr/lib/systemd/system/pki-tomcatd@.service
[Unit]
Description=PKI Tomcat Server %i
PartOf=pki-tomcatd.target

[Service]
Type=simple
EnvironmentFile=/usr/share/pki/etc/tomcat.conf
EnvironmentFile=/etc/tomcat/tomcat.conf
Environment="NAME=%i"
EnvironmentFile=-/etc/sysconfig/%i
EnvironmentFile=/usr/share/pki/etc/pki.conf
EnvironmentFile=/etc/pki/pki.conf
....
```

Java security access manager is configured to allow access to `/var/lib/pki/pki-tomcat` resources then but in container we have everything in `/data/var/lib/pki/pki-tomcat` and that might be breaking it. If your `/etc/sysconfig/pki-tomcat` file has non-prefixed path, it might be the reason.

**Comment by abbra** [comment] 2024-02-28 07:54
I hoped it would be the case. So the question here is more of what else is wrong. Note that this repointing of 4.9 to 4.10 via change of RockyLinux 8 to RockyLinux 9 is not something tested by the upstream at all. In fact, we *do not* support RHEL 8 to RHEL 9 inplace upgrade at all.

**Comment by m3e-g** [comment] 2024-02-28 08:50
Is there any supported update path? From my understanding the `ipa-backup` and `ipa-restore` are not supported on containers due to unexpected symlinks, but even if they ware, they still should be used on the same version, right?

**Comment by abbra** [comment] 2024-02-28 08:55
The supported upgrade path across different distribution major versions is described in the documentation: you have to use a new replica: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/migrating_to_identity_management_on_rhel_9/index#migrating_idm_from_rhel_8_to_rhel_9

**Comment by adelton** [comment] 2024-03-01 06:36
I confirm that I was able to reproduce the problem by running
```
docker=podman tests/run-partial-tests.sh Dockerfile.fedora-39
```
and then letting the container sit there across the midnight. I then got
```
Feb 29 00:03:17 ipa.example.test server[4514]: java.util.logging.ErrorManager: 1: FileHandler is closed or not yet initialized, unable to log [2024-02-29 00:03:17 [CRLIssuingPoint-MasterCRL] WARNING: Cannot update CRL cache. Error: java.security.AccessControlException: access denied ("java.io.FilePermission" "/data/var/lib/pki/pki-tomcat/logs/ca" "read")
Feb 29 00:03:17 ipa.example.test server[4514]: ]
Feb 29 00:03:18 ipa.example.test server[4514]: java.util.logging.ErrorManager: 1: FileHandler is closed or not yet initialized, unable to log [2024-02-29 00:03:18 [pool-1-thread-1] SEVERE: Unable to run maintenance task: access denied ("java.io.FilePermission" "/data/var/lib/pki/pki-tomcat/logs/acme" "read")
Feb 29 00:03:18 ipa.example.test server[4514]: java.security.AccessControlException: access denied ("java.io.FilePermission" "/data/var/lib/pki/pki-tomcat/logs/acme" "read")
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.io.File.exists(File.java:829)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.io.File.mkdirs(File.java:1403)
Feb 29 00:03:18 ipa.example.test server[4514]:         at org.apache.juli.FileHandler.openWriter(FileHandler.java:428)
Feb 29 00:03:18 ipa.example.test server[4514]:         at org.apache.juli.FileHandler.publish(FileHandler.java:220)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.logging/java.util.logging.Logger.log(Logger.java:980)
Feb 29 00:03:18 ipa.example.test server[4514]:         at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
Feb 29 00:03:18 ipa.example.test server[4514]:         at org.slf4j.impl.JDK14LoggerAdapter.info(JDK14LoggerAdapter.java:277)
Feb 29 00:03:18 ipa.example.test server[4514]:         at org.dogtagpki.acme.scheduler.ACMEMaintenanceTask.run(ACMEMaintenanceTask.java:22)
Feb 29 00:03:18 ipa.example.test server[4514]:         at org.dogtagpki.acme.scheduler.ACMEScheduler$1.run(ACMEScheduler.java:59)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Feb 29 00:03:18 ipa.example.test server[4514]:         at java.base/java.lang.Thread.run(Thread.java:840)
Feb 29 00:03:18 ipa.example.test server[4514]: ]
```

**Comment by abbra** [comment] 2024-03-01 07:38
I see this issue on a non-containerized deployment of F39 as well. I think the best way forward is to report this to PKI folks. There is nothing we can do with this in FreeIPA or in the container project: these configurations are fully owned by the dogtag code.

**Comment by adelton** [comment] 2024-03-01 11:51
I've reproduced it on RHEL 9.3 as well and reported it as https://issues.redhat.com/browse/RHEL-27610.

**Comment by adelton** [comment] 2024-03-01 11:54
@m3e-g Seeing this is a generic FreeIPA / IdM / PKI issue, I'll go ahead and close this report because at this point we don't expected any freeipa-container specific fix or action.

I'll be watching that RHEL issue and when it gets fixed, I'll recheck it in the containerized setup to make sure the `/data` use case is also working fine.

**Comment by adelton** [comment] 2024-03-01 11:54
Thanks @abbra for the investigation.

**Closed by adelton** 2024-03-01 11:54 UTC
