### ISSUE TITLE
Services automatically exits and container loses internet access when restarted

### ISSUE THREAD

**Issue by JoyceBabu** [freeipa/freeipa-container#99] opened 2016-12-06 11:03 UTC
When the `--setup-dns` option is used, the services does not stay running on restarting the container.

**docker-compose.yml**
```yml
version: "2"
services:
    freeipa:
        container_name: freeipa
        image: adelton/freeipa-server:fedora-25
        restart: always
        hostname: freeipa
        domainname: example.com
        environment:
            - HOSTNAME=freeipa.example.com
            - IPA_SERVER_IP=10.10.0.106
            - IPA_SERVER_HOSTNAME=freeipa.example.com
        volumes:
            - ./data/:/data:Z
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        networks:
            net-external:
                ipv4_address: "10.10.0.106"
        tty: true
        stdin_open: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - "seccomp:unconfined"
        command:  --domain=example.com --realm=example.com --http-pin=testpass --dirsrv-pin=testpass --ds-password=testpass --admin-password=testpass -U --no-host-dns --no-dnssec-validation --setup-dns --auto-forwarders --allow-zone-overlap --unattended

networks:
    net-external:
      external: true
```

The container is working fine when I run `docker-compose up`.

But if I do `docker-compose stop && docker-compose up`, then the services running inside the container automatically exits a few seconds after the container is restarted.

**Comment by JoyceBabu** [comment] 2016-12-06 11:33
Also, `dnf install` too stops working after container restart. I am getting the error

> Error: Failed to synchronize cache for repo 'fedora'

**Comment by adelton** [comment] 2016-12-09 15:10
> Also, dnf install too stops working after container restart. I am getting the error
> 
>     Error: Failed to synchronize cache for repo 'fedora'
> 
> Update: The container is unable to connect to the internet after restarting.
> 
>     [root@freeipa /]# curl -I http://www.google.com/
>     curl: (6) Could not resolve host: www.google.com

These all are sort of expected is the named in the container does not start because the `resolv.conf` in the container points to localhost (the container), so even forwarding will now work.

**Comment by adelton** [comment] 2016-12-09 15:11
> But if I do docker-compose stop && docker-compose up, then the services running inside the container automatically exits a few seconds after the container is restarted.

Can you mange to run `systemctl status named-pkcs11 -l` in the container (before the `systemd` there dies)?

**Comment by JoyceBabu** [comment] 2016-12-12 14:06
> Can you mange to run systemctl status named-pkcs11 -l in the container (before the systemd there dies)?

```
[root@freeipa /]# systemctl status named-pkcs11 -l
* named-pkcs11.service - Berkeley Internet Name Domain (DNS) with native PKCS#11
   Loaded: loaded (/usr/lib/systemd/system/named-pkcs11.service; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2016-12-12 13:54:50 UTC; 10s ago
  Process: 501 ExecStart=/usr/sbin/named-pkcs11 -u named $OPTIONS (code=exited, status=1/FAILURE)
  Process: 499 ExecStartPre=/bin/bash -c if [ ! "$DISABLE_ZONE_CHECKING" == "yes" ]; then /usr/sbin/named-checkconf -z /etc/named.conf; else echo "Checking of zone files is disabled"; fi (code=exited, status=0/SUCCESS)

Dec 12 13:54:10 example.com named-pkcs11[502]: bind-dyndb-ldap version 10.0 compiled at 16:18:01 Jul 27 2016, compiler 6.1.1 20160721 (Red Hat 6.1.1-4)
Dec 12 13:54:10 example.com named-pkcs11[502]: option 'serial_autoincrement' is not supported, ignoring
Dec 12 13:54:30 example.com named-pkcs11[502]: GSSAPI client step 1
Dec 12 13:54:30 example.com named-pkcs11[502]: GSSAPI client step 1
Dec 12 13:54:50 example.com named-pkcs11[502]: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server ldap/example.com@EXAMPLE.COM not found in Kerberos database)
Dec 12 13:54:50 example.com named-pkcs11[502]: LDAP error: Local error: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server ldap/example.com@EXAMPLE.COM not found in
 Kerberos database): bind to LDAP server failed
Dec 12 13:54:50 example.com systemd[1]: named-pkcs11.service: Control process exited, code=exited status=1
Dec 12 13:54:50 example.com systemd[1]: Failed to start Berkeley Internet Name Domain (DNS) with native PKCS#11.
Dec 12 13:54:50 example.com systemd[1]: named-pkcs11.service: Unit entered failed state.
Dec 12 13:54:50 example.com systemd[1]: named-pkcs11.service: Failed with result 'exit-code'.
```

<hr>

Systemd does not completely exit. But most of the running services like `named`, `httpd` are killed. When starting the container for the first time, I can see that there are 30 ports open.

```
[root@example /]# netstat -tulpn | wc -l
30
[root@example /]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:88              0.0.0.0:*               LISTEN      2735/krb5kdc        
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:749             0.0.0.0:*               LISTEN      2061/kadmind        
tcp        0      0 0.0.0.0:464             0.0.0.0:*               LISTEN      2061/kadmind        
tcp        0      0 10.10.0.106:53          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.11:39190        0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::88                   :::*                    LISTEN      2735/krb5kdc        
tcp6       0      0 ::1:953                 :::*                    LISTEN      -                   
tcp6       0      0 :::443                  :::*                    LISTEN      3110/httpd          
tcp6       0      0 :::8443                 :::*                    LISTEN      -                   
tcp6       0      0 :::636                  :::*                    LISTEN      -                   
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN      -                   
tcp6       0      0 :::389                  :::*                    LISTEN      -                   
tcp6       0      0 ::1:8009                :::*                    LISTEN      -                   
tcp6       0      0 :::749                  :::*                    LISTEN      2061/kadmind        
tcp6       0      0 :::80                   :::*                    LISTEN      3110/httpd          
tcp6       0      0 :::8080                 :::*                    LISTEN      -                   
tcp6       0      0 :::464                  :::*                    LISTEN      2061/kadmind        
tcp6       0      0 :::53                   :::*                    LISTEN      -                   
udp        0      0 10.10.0.106:53          0.0.0.0:*                           -                   
udp        0      0 127.0.0.1:53            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:88              0.0.0.0:*                           2735/krb5kdc        
udp        0      0 0.0.0.0:464             0.0.0.0:*                           2061/kadmind        
udp        0      0 127.0.0.11:60268        0.0.0.0:*                           -                   
udp6       0      0 :::53                   :::*                                -                   
udp6       0      0 :::88                   :::*                                2735/krb5kdc        
udp6       0      0 :::464                  :::*                                2061/kadmind        

```

But after restarting

```
[root@example /]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:44185        0.0.0.0:*               LISTEN      -                   
udp        0      0 0.0.0.0:33653           0.0.0.0:*                           639/host            
udp        0      0 127.0.0.11:58072        0.0.0.0:*                           -       
```


```
[root@example /]# systemctl list-unit-files
UNIT FILE                                 STATE 
proc-sys-fs-binfmt_misc.automount         bad   
org.freedesktop.hostname1.busname         bad   
org.freedesktop.locale1.busname           bad   
org.freedesktop.login1.busname            bad   
org.freedesktop.network1.busname          bad   
org.freedesktop.resolve1.busname          bad   
org.freedesktop.systemd1.busname          bad   
org.freedesktop.timedate1.busname         bad   
dev-hugepages.mount                       bad   
dev-mqueue.mount                          bad   
proc-fs-nfsd.mount                        bad   
proc-sys-fs-binfmt_misc.mount             bad   
sys-fs-fuse-connections.mount             bad   
sys-kernel-config.mount                   bad   
sys-kernel-debug.mount                    bad   
tmp.mount                                 bad   
var-lib-nfs-rpc_pipefs.mount              bad   
systemd-ask-password-console.path         bad   
systemd-ask-password-wall.path            bad   
arp-ethers.service                        bad   
auditd.service                            bad   
auth-rpcgss-module.service                bad   
autofs.service                            bad   
autovt@.service                           bad   
certmonger.service                        bad   
console-getty.service                     bad   
console-shell.service                     bad   
container-getty@.service                  bad   
dbus-org.freedesktop.hostname1.service    bad   
dbus-org.freedesktop.locale1.service      bad   
dbus-org.freedesktop.login1.service       bad   
dbus-org.freedesktop.network1.service     bad   
dbus-org.freedesktop.resolve1.service     bad   
dbus-org.freedesktop.timedate1.service    bad   
dbus.service                              bad   
debug-shell.service                       bad   
dirsrv-snmp.service                       bad   
dirsrv@.service                           bad   
dnf-makecache.service                     bad   
emergency.service                         bad   
fedora-domainname.service                 bad   
fedora-import-state.service               bad   
fedora-loadmodules.service                bad   
fedora-readonly.service                   bad   
fstrim.service                            bad   
getty@.service                            bad   
gssproxy.service                          bad   
halt-local.service                        bad   
htcacheclean.service                      bad   
httpd.service                             bad   
initrd-cleanup.service                    bad   
initrd-parse-etc.service                  bad   
initrd-switch-root.service                bad   
ipa-custodia.service                      bad   
ipa-dnskeysyncd.service                   bad   
ipa-ods-exporter.service                  bad   
ipa-otpd@.service                         bad   
ipa-server-configure-first.service        bad   
ipa-server-update-self-ip-address.service bad   
ipa-server-upgrade.service                bad   
ipa.service                               bad   
ipa_memcached.service                     bad   
kadmin.service                            bad   
kill-tail.service                         bad   
kprop.service                             bad   
krb5kdc.service                           bad   
ldconfig.service                          bad   
memcached.service                         bad   
messagebus.service                        bad   
named-pkcs11.service                      bad   
named-setup-rndc.service                  bad   
named.service                             masked
netconsole.service                        masked
network.service                           masked
nfs-blkmap.service                        bad   
nfs-config.service                        bad   
nfs-idmap.service                         bad   
nfs-idmapd.service                        bad   
nfs-lock.service                          bad   
nfs-mountd.service                        bad   
nfs-secure.service                        bad   
nfs-server.service                        bad   
nfs-utils.service                         bad   
nfs.service                               bad   
nmb.service                               bad   
ntpd.service                              bad   
ntpdate.service                           bad   
oddjobd.service                           bad   
ods-enforcerd.service                     bad   
ods-signerd.service                       bad   
pkcsslotd.service                         bad   
pki-tomcatd-nuxwdog@.service              bad   
pki-tomcatd@.service                      bad   
polkit.service                            bad   
rc-local.service                          bad   
rdisc.service                             bad   
rescue.service                            bad   
rpc-gssd.service                          bad   
rpc-statd-notify.service                  bad   
rpc-statd.service                         bad   
rpcbind.service                           bad   
selinux-autorelabel-mark.service          bad   
selinux-autorelabel.service               bad   
serial-getty@.service                     bad   
smb.service                               bad   
sssd-secrets.service                      bad   
sssd.service                              bad   
systemd-ask-password-console.service      bad   
systemd-ask-password-wall.service         bad   
systemd-binfmt.service                    bad   
systemd-coredump@.service                 bad   
systemd-exit.service                      bad   
systemd-firstboot.service                 bad   
systemd-fsck-root.service                 bad   
systemd-fsck@.service                     bad   
systemd-halt.service                      bad   
systemd-hostnamed.service                 bad   
systemd-initctl.service                   bad   
systemd-journal-catalog-update.service    bad   
systemd-journal-flush.service             bad   
systemd-journald.service                  bad   
systemd-kexec.service                     bad   
systemd-localed.service                   bad   
systemd-logind.service                    bad   
systemd-machine-id-commit.service         bad   
systemd-networkd-wait-online.service      bad   
systemd-networkd.service                  bad   
systemd-poweroff.service                  bad   
systemd-reboot.service                    bad   
systemd-remount-fs.service                bad   
systemd-resolved.service                  bad   
systemd-sysctl.service                    bad   
systemd-sysusers.service                  bad   
systemd-timedated.service                 bad   
systemd-tmpfiles-clean.service            bad   
systemd-tmpfiles-setup.service            bad   
systemd-update-done.service               bad   
systemd-update-utmp-runlevel.service      bad   
systemd-update-utmp.service               bad   
systemd-user-sessions.service             bad   
timedatex.service                         bad   
tomcat.service                            bad   
tomcat@.service                           bad   
user@.service                             bad   
winbind.service                           bad   
-.slice                                   bad   
system.slice                              bad   
user.slice                                bad   
dbus.socket                               bad   
httpd.socket                              bad   
ipa-ods-exporter.socket                   bad   
ipa-otpd.socket                           bad   
rpcbind.socket                            bad   
sssd-secrets.socket                       bad   
syslog.socket                             bad   
systemd-coredump.socket                   bad   
systemd-initctl.socket                    bad   
systemd-journald-audit.socket             bad   
systemd-journald-dev-log.socket           bad   
systemd-journald.socket                   bad   
systemd-networkd.socket                   bad   
basic.target                              masked
bluetooth.target                          bad   
busnames.target                           bad   
container-ipa.target                      bad   
cryptsetup-pre.target                     bad   
cryptsetup.target                         bad   
ctrl-alt-del.target                       bad   
default.target                            bad   
dirsrv.target                             bad   
emergency.target                          bad   
exit.target                               bad   
final.target                              bad   
getty.target                              bad   
graphical.target                          bad   
halt.target                               bad   
hibernate.target                          bad   
hybrid-sleep.target                       bad   
initrd-fs.target                          bad   
initrd-root-device.target                 bad   
initrd-root-fs.target                     bad   
initrd-switch-root.target                 bad   
initrd.target                             bad   
kexec.target                              bad   
local-fs-pre.target                       bad   
local-fs.target                           bad   
multi-user.target                         bad   
network-online.target                     bad   
network-pre.target                        bad   
network.target                            bad   
nfs-client.target                         bad   
nss-lookup.target                         bad   
nss-user-lookup.target                    bad   
paths.target                              bad   
pki-tomcatd-nuxwdog.target                bad   
pki-tomcatd.target                        bad   
poweroff.target                           bad   
printer.target                            bad   
reboot.target                             bad   
remote-fs-pre.target                      bad   
remote-fs.target                          bad   
rescue.target                             bad   
rpcbind.target                            bad   
runlevel0.target                          bad   
runlevel1.target                          bad   
runlevel2.target                          bad   
runlevel3.target                          bad   
runlevel4.target                          bad   
runlevel5.target                          bad   
runlevel6.target                          bad   
selinux-autorelabel.target                bad   
shutdown.target                           bad   
sigpwr.target                             bad   
sleep.target                              bad   
slices.target                             bad   
smartcard.target                          bad   
sockets.target                            bad   
sound.target                              bad   
suspend.target                            bad   
swap.target                               bad   
sysinit.target                            bad   
system-update.target                      bad   
time-sync.target                          bad   
timers.target                             bad   
umount.target                             bad   
dnf-makecache.timer                       bad   
fstrim.timer                              bad   
systemd-tmpfiles-clean.timer              bad   
```

**Comment by bazsi** [comment] 2016-12-31 08:29
I seem to have run into the same issue. I am not sure what I am doing wrong, but all works in the first boot, but after restart it just kills off processes after a couple of seconds.

Consulting the audit log, it seems that ipactl stops those services explicitly, after named-pkcs11 fails to start.

If I specify --ignore-service-failures it runs:
```
[root@sch /]# /usr/sbin/ipactl --ignore-service-failures start
Existing service file detected!
Assuming stale, cleaning and proceeding
Starting Directory Service
Starting krb5kdc Service
Starting kadmin Service
Starting named Service
Failed to start named Service
Forced start, ignoring named Service, continuing normal operation
Starting ipa_memcached Service
Starting httpd Service
Starting ipa-custodia Service
Starting pki-tomcatd Service
Starting ipa-otpd Service
Starting ipa-dnskeysyncd Service
ipa: INFO: The ipactl command was successful
```

**Comment by bazsi** [comment] 2016-12-31 08:32
This seems to be the culprit:

```
Dec 31 08:25:17 sch.lan named-pkcs11[455]: GSSAPI client step 1
Dec 31 08:25:17 sch.lan named-pkcs11[455]: GSSAPI client step 1
Dec 31 08:25:37 sch.lan named-pkcs11[455]: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server ldap/sch.lan@SCH.LA
N not found in Kerberos database)
Dec 31 08:25:37 sch.lan named-pkcs11[455]: LDAP error: Local error: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may 
provide more information (Server ldap/sch.lan@SCH.LAN not found in Kerberos database): bind to LDAP server failed
```
Now, with the KDC running, I tried to kvno ldap/sch.lan@SCH.LAN and that principal indeed does not exist.

**Comment by bazsi** [comment] 2016-12-31 08:41
hmm.. this seems that the ldap principal name should read: ```ldap/ipa.sch.lan@SCH.LAN```
And instead it is ```ldap/sch.lan@SCH.LAN```

I've noticed that ipa changes the hostname to sch.lan, even though the hostname specified is ipa.sch.lan.

**Comment by adelton** [comment] 2017-01-09 08:46
I believe it's an instance of bug https://bugzilla.redhat.com/show_bug.cgi?id=1404750.

**Comment by adelton** [comment] 2017-02-11 10:06
Can you please try the current master?

The 6e359d3ffdb4b44564988ab1cb9d4e48a8369d26 change should address the issue.

**Comment by JoyceBabu** [comment] 2017-02-11 13:45
I tried with Fedora 25 [Dockerfile](https://github.com/freeipa/freeipa-container/blob/master/Dockerfile) and got the same error.

**Comment by meyerds** [comment] 2017-02-14 03:46
I'm also having this problem on CentOS 7 with the latest :centos-7 image.

**Comment by adelton** [comment] 2017-03-13 15:11
To step back a bit -- if you run it outside of `docker-compose`, and as privileged container -- do things work, even after restart?

**Comment by Trisooma** [comment] 2017-05-14 19:47
Just to chime it, i'm running into the same issue. I am not running this through compose (and not as a privileged container).

**Comment by adelton** [comment] 2017-05-15 09:03
> Just to chime it, i'm running into the same issue. I am not running this through compose (and not as a privileged container).

Please open new issue with OS/docker environment information and steps to reproduce outside of `docker-compose`.

**Comment by JoyceBabu** [comment] 2017-06-26 12:09
Sorry for the late response.

I tried it outside `docker-compose`, and it still exists.

**Comment by adelton** [comment] 2018-07-05 07:12
We don't seem to have enough information to investigate, closing.

**Closed by adelton** 2018-07-05 07:12 UTC
