### ISSUE TITLE
First IPA master adds A record for ipa-ca to container address

### ISSUE THREAD

**Issue by dcode** [freeipa/freeipa-container#321] opened 2020-05-15 22:57 UTC
I created a master on one host, then created a replica on another host. Prior to creating the replica, the only IP in the `ipa-ca` A record was the container IP (10.88.2.174 in the screenshot). Once I created the replica, this was updated with the two IPs of the servers.

I'm running using podman, and passed in `IPA_SERVER_HOSTNAME` and `IPA_SERVER_IP` as suggested in the docs, but that didn't seem to prevent the initial container IP leakage.

```
    -e IPA_SERVER_HOSTNAME=ipa01.example.lan \
    -e IPA_SERVER_IP=192.168.1.52 \
```

Screenshot:
<img width="894" alt="Screen Shot 2020-05-15 at 5 47 51 PM" src="https://user-images.githubusercontent.com/171574/82102172-4995ab00-96d4-11ea-8697-b20f579eef56.png">

I'm using the current `latest` image:

$ sudo podman images
```
REPOSITORY                         TAG      IMAGE ID       CREATED       SIZE
docker.io/freeipa/freeipa-server   latest   2bedea2a6293   10 days ago   812 MB
```

## Install parameters

I used the following install line for the initial run:

```
/usr/bin/podman run \
  --name freeipa-server.service \
  --detach \
    --publish 53:53/udp \
    --publish 53:53/tcp \
    --publish 80:80/tcp \
    --publish 443:443/tcp \
    --publish 389:389/tcp \
    --publish 636:636/tcp \
    --publish 123:123/udp \
    --publish 88:88/tcp \
    --publish 88:88/udp \
    --publish 464:464/tcp \
    --publish 464:464/udp \
    --volume freeipa-server-data:/data:Z \
    --volume /etc/named/ipa-ext.conf:/data/etc/named/ipa-ext.conf:ro \
    -e IPA_SERVER_HOSTNAME=ipa01.example.lan \
    -e IPA_SERVER_IP=192.168.1.52 \
    docker.io/freeipa/freeipa-server:latest \
      exit-on-finished \
      --setup-dns \
      --forwarder=1.1.1.1 \
      --forwarder=1.0.0.1 \
      --forward-policy=only \
      --mkhomedir \
      --ssh-trust-dns \
      --no-ntp \
      --realm=EXAMPLE.LAN \
      --domain=example.lan \
      --ds-password=<random password> \
      --admin-password=<random password> \
      --unattended
```

**Comment by adelton** [comment] 2020-05-18 07:58
Do I read it right that the concern is the master's container IP address used for the `ipa-ca` A record instead of the `IPA_SERVER_IP` value, and the replica's role in this setup is to only show that after it was added, its `IPA_SERVER_IP` value was correctly used, and also the master's `IPA_SERVER_IP` got suddenly correctly added?

**Comment by adelton** [comment] 2020-05-18 09:01
I did a quick test run and it seems that if you use `--ip-address=192.168.1.52` option to `ipa-server-install`, the `ipa-ca` will be set to that address. You likely still want that `-e IPA_SERVER_IP=192.168.1.52` option to `podman run` as well, or the IP address of `ipa01.example.lan` won't be set right.

Overall, I was never quite happy with the `ipa-ca` feature of FreeIPA, it seemed too automagic and hard to control, even outside of containers. So in containers we are really just trying to find reasonable ways of pleasing the `ipa-server-install` logic which isn't (or at least until recently was not) friendly to setups where the internally-visible network interfaces (internally == on the FreeIPA server) do not match how the server is accessed from outside.

**Comment by adelton** [comment] 2020-05-26 07:40
@dcode Did the combination of `-e IPA_SERVER_IP=192.168.1.52` and `--ip-address=192.168.1.52` yield acceptable results for you?

**Comment by dcode** [comment] 2020-05-26 18:06
sorry for the lag, somehow didn't get notified until you tagged me this morning. You did interpret my issue correctly. I hadn't tried the `--ip-address` flag per the README

> Note that an attempt of achieving this goal with the --ip-address option of ipa-server-install command is likely to fail, and should be avoided.

I did like you said w/ the env variable and the flag both and that worked out for me. Thanks! Maybe we just update those docs and close this?

**Comment by adelton** [comment] 2020-05-27 08:11
Right. I was aware of the note about the `--ip-address` in the documentation. In the past, the `ipa-server-install` fail when IP address was specified for which interface did not exist in the environment -- https://bugzilla.redhat.com/show_bug.cgi?id=1377973. We then added patches for that in the container image, and it seems to be fixed in the latest FreeIPAs and the patches are no longer needed.

What I'd like to do is to add tests for the setup in the CI before changing the recommendation in the README and get more understanding of what the right approach should be. Using `--ip-address=192.168.1.52` does not seem to be enough to force the use of that (non-local) IP address for the FreeIPA server hostname A record. We should figure out if that is a problem with the way we do things in the containers or if it's happening outside of containers as well, affecting for example AWS setups. In the second case it would need to be reported against FreeIPA itself.

**Comment by adelton** [comment] 2020-09-13 07:58
@frasertweedale, any suggestions about the correct handling of IP addresses where the IP addresses as seen by the FreeIPA server are internal ones that should never be advertised via DNS or otherwise? I assume FreeIPA on EC2 might be in the same situation when only the public IP addresses that NAT the access to the FreeIPA server should typically be used.

**Comment by abbra** [comment] 2020-09-13 09:42
We do not have any mechanism to split IP addresses by categories when updating DNS entries. It would require a completely new code in IPA to do so. I think this is something we'll need anyway for future but currently nobody works on this.

**Comment by frasertweedale** [comment] 2020-09-14 02:50
@adelton we are still not 100% sure, but for OpenShift environment and with freeipa-operator we are leaning toward managing DNS outside of FreeIPA.  At the very least, the operator may have to manage DNS records in the IPA integrated DNS, using information that is not necessarily observable within the container(s).

**Comment by adelton** [comment] 2021-01-07 09:40
I tried a couple of approaches and test deployments and I have the following questions, likely on @abbra and @frasertweedale:

What is the primary information about FreeIPA server's IP address? Is it `ipa dnsrecord-find example.test --name=ipa` or is it stored somewhere else?

When DNS server is not deployed in the FreeIPA cluster, does the cluster keep any information about IP addresses of its servers anywhere?

Without DNS server, `ipa dns-update-system-records --dry-run` does not show any A-record related information. Is that expected?

Does the `--ip-address` option to `ipa-server-install` have any meaning when `--setup-dns` is not used?

What is the recommended way of updating FreeIPA server's IP address? Is it `ipa dnsrecord-mod example.test ipa --a-rec=aa.bb.cc.dd` followd by `ipa dns-update-system-records` to update the `ipa-ca` record(s), or direct `nsupdate`?

**Comment by adelton** [comment] 2022-01-02 07:34
@abbra, @frasertweedale Would you have some answers to the questions above? I seem to have hit the limits of my understanding how things are expected to be structured and where to find the information needed. Thank you.

**Comment by adelton** [comment] 2022-01-02 08:00
Note to self: one implication of using `--ip-address` is https://pagure.io/freeipa/issue/8888, discussed in https://github.com/freeipa/freeipa-container/issues/383#issuecomment-864605076.

**Comment by rcritten** [comment] 2022-01-04 14:50
> What is the primary information about FreeIPA server's IP address? Is it `ipa dnsrecord-find example.test --name=ipa` or is it stored somewhere else?

It is stored only in DNS and /etc/hosts AFAIK.
 
> When DNS server is not deployed in the FreeIPA cluster, does the cluster keep any information about IP addresses of its servers anywhere?

Same as above.

> Without DNS server, `ipa dns-update-system-records --dry-run` does not show any A-record related information. Is that expected?

I know its been a year since you originally posed the question but I can't reproduce this with semi-current HEAD. I get an A record for ipa-ca. Is that the A-record you are asking about?
 
> Does the `--ip-address` option to `ipa-server-install` have any meaning when `--setup-dns` is not used?

It will be the value used in /etc/hosts at least. I couldn't find any other changes but there could be something subtle I missed.
 
> What is the recommended way of updating FreeIPA server's IP address? Is it `ipa dnsrecord-mod example.test ipa --a-rec=aa.bb.cc.dd` followd by `ipa dns-update-system-records` to update the `ipa-ca` record(s), or direct `nsupdate`?

I'll defer to others on this one. @rjeffman may have some thoughts.

**Comment by adelton** [comment] 2022-03-31 20:14
> > Without DNS server, `ipa dns-update-system-records --dry-run` does not show any A-record related information. Is that expected?
> 
> I know its been a year since you originally posed the question but I can't reproduce this with semi-current HEAD. I get an A 
record for ipa-ca. Is that the A-record you are asking about?

I confirm I see A and AAAA records for ipa-ca, with freeipa-server-4.9.3-1.fc32.x86_64 and freeipa-server-4.9.8-1.fc35.x86_64.

I have no idea what I saw or meant back then. :-)

Thank you for your answers @rcritten, appreciated.

**Comment by adelton** [comment] 2023-01-22 14:16
In `master`, I've now updated the K3s tests to use the `--ip-address`, and I've updated the README to prefer the `--ip-address` approach.

**Closed by adelton** 2023-01-22 14:16 UTC

**Comment by adalsa91** [comment] 2023-07-27 13:03
I'm not sure what the conclusion is. I tried to use `--ip-addres` flag and `ipa-ca` is set to container address, I tried to use both `--ip-addres` and  `-e IPA_SERVER_IP=...` and same result. In the README it said that:

> Alternatively, the IPA_SERVER_IP environment variable via the -e option to docker run / podman run can be used to define what IP address should the FreeIPA server put to DNS as its address. Using this mechanism will however not update the ipa-ca record.

So... there is no way to set `ipa-ca` to the IP of the hosts instead of the container?
