### ISSUE TITLE
Services do not come up after restarting container (after succesfull installation)

### ISSUE THREAD

**Issue by Trisooma** [freeipa/freeipa-container#135] opened 2017-05-15 20:43 UTC
Hi,

I am trying to install the latest version of freeipa-container(fedora-25) on my docker host (17.03.0-ce), previous versions have been running without any problems.
```
[setup@spark ~]$ uname -a
Linux spark.example.com 4.6.6-300.fc24.x86_64 #1 SMP Wed Aug 10 21:07:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
I installed freeipa-container using the following command:
```
docker run --name freeipa -it \
    --security-opt seccomp=unconfined \
    --hostname ipa.example.com \
    --volume /data/DockerAppData/freeipa:/data \
    --volume /etc/localtime:/etc/localtime:ro \
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
    --cap-add SYS_ADMIN \
    --cap-add SYS_TIME \
    --publish 192.168.134.2:80:80 \
    --publish 192.168.134.2:443:443 \
    --publish 192.168.134.2:389:389 \
    --publish 192.168.134.2:636:636 \
    --publish 192.168.134.2:88:88 \
    --publish 192.168.134.2:464:464 \
    --publish 192.168.134.2:53:53 \
    --publish 192.168.134.2:88:88/udp \
    --publish 192.168.134.2:464:464/udp \
    --publish 192.168.134.2:53:53/udp \
    --publish 192.168.134.2:123:123/udp \
    --publish 192.168.134.2:135:135 \
    --publish 192.168.134.2:138:138 \
    --publish 192.168.134.2:139:139 \
    --publish 192.168.134.2:445:445 \
    --publish 192.168.134.2:1024:1024 \
    --publish 192.168.134.2:138:138/udp \
    --publish 192.168.134.2:139:139/udp \
    --publish 192.168.134.2:389:389/udp \
    --publish 192.168.134.2:445:445/udp \
    --env container=docker \
    --memory 2048M \
    --memory-swap 2048M \
    adelton/freeipa-server:fedora-25
```
Installation is successful and I can enroll machines into the domain. After removing and restarting the container services fail to start. The command I use to start the container is exactly the same as above, except I replaced `-it` with `-d`.

Before restarting the container (after successful install), this is what I get:
```
[root@example /]# systemctl status named-pkcs11 -l
* named-pkcs11.service - Berkeley Internet Name Domain (DNS) with native PKCS#11
   Loaded: loaded (/usr/lib/systemd/system/named-pkcs11.service; bad; vendor preset: disabled)
   Active: active (running) since Mon 2017-05-15 21:29:23 CEST; 24min ago
 Main PID: 3209 (named-pkcs11)
    Tasks: 8 (limit: 4915)
   CGroup: /docker/1eefcc4903b2bc5db92d90c2e43fdf3860e0620aec84d83c676e0488a1303a27/system.slice/named-pkcs11.service
           `-3209 /usr/sbin/named-pkcs11 -u named

May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-235.awsdns-29.com/A/IN': 2600:9000:5304:9d00::1#53
May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-235.awsdns-29.com/A/IN': 2600:9000:5306:dd00::1#53
May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-418.awsdns-52.com/AAAA/IN': 2600:9000:5300:3500::1#53
May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-418.awsdns-52.com/AAAA/IN': 2600:9000:5304:b400::1#53
May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-418.awsdns-52.com/AAAA/IN': 2600:9000:5302:7400::1#53
May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-1306.awsdns-35.org/A/IN': 2600:9000:5304:2600::1#53
May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-1306.awsdns-35.org/A/IN': 2600:9000:5300:a300::1#53
May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-1414.awsdns-48.org/A/IN': 2600:9000:5300:b000::1#53
May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-1414.awsdns-48.org/A/IN': 2600:9000:5302:f200::1#53
May 15 21:53:18 example.com named-pkcs11[3209]: network unreachable resolving 'ns-1414.awsdns-48.org/A/IN': 2600:9000:5304:3300::1#53
```
```
[root@example /]# netstat -tulpn | wc -l
32
[root@example /]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:749             0.0.0.0:*               LISTEN      2137/kadmind
tcp        0      0 0.0.0.0:464             0.0.0.0:*               LISTEN      2137/kadmind
tcp        0      0 192.168.136.4:53        0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:88              0.0.0.0:*               LISTEN      2833/krb5kdc
tcp6       0      0 :::8443                 :::*                    LISTEN      -
tcp6       0      0 :::443                  :::*                    LISTEN      3238/httpd
tcp6       0      0 :::636                  :::*                    LISTEN      -
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN      -
tcp6       0      0 :::389                  :::*                    LISTEN      -
tcp6       0      0 127.0.0.1:8009          :::*                    LISTEN      -
tcp6       0      0 :::749                  :::*                    LISTEN      2137/kadmind
tcp6       0      0 :::8080                 :::*                    LISTEN      -
tcp6       0      0 :::464                  :::*                    LISTEN      2137/kadmind
tcp6       0      0 :::80                   :::*                    LISTEN      3238/httpd
tcp6       0      0 :::53                   :::*                    LISTEN      -
tcp6       0      0 :::88                   :::*                    LISTEN      2833/krb5kdc
udp        0      0 192.168.136.4:53        0.0.0.0:*                           -
udp        0      0 127.0.0.1:53            0.0.0.0:*                           -
udp        0      0 0.0.0.0:88              0.0.0.0:*                           2833/krb5kdc
udp        0      0 192.168.136.4:123       0.0.0.0:*                           -
udp        0      0 127.0.0.1:123           0.0.0.0:*                           -
udp        0      0 0.0.0.0:123             0.0.0.0:*                           -
udp        0      0 0.0.0.0:464             0.0.0.0:*                           2137/kadmind
udp6       0      0 :::53                   :::*                                -
udp6       0      0 :::88                   :::*                                2833/krb5kdc
udp6       0      0 fe80::42:c0ff:fea8::123 :::*                                -
udp6       0      0 ::1:123                 :::*                                -
udp6       0      0 :::123                  :::*                                -
udp6       0      0 :::464                  :::*                                2137/kadmind
```
After restarting the container, it looks like it's trying to start all services but it fails after a while:
```
[root@example /]# ipactl status
Directory Service: STOPPED
Directory Service must be running in order to obtain status of other services
ipa: INFO: The ipactl command was successful
```
Trying to ignore failures gives:
```
[root@example /]# ipactl --ignore-service-failures start
Existing service file detected!
Assuming stale, cleaning and proceeding
Starting Directory Service
Starting krb5kdc Service
Starting kadmin Service
Starting named Service
Failed to start named Service
Forced start, ignoring named Service, continuing normal operation
Starting ipa_memcached Service
Starting httpd Service
Starting ipa-custodia Service
Starting ntpd Service
Starting pki-tomcatd Service
Starting ipa-otpd Service
Starting ipa-dnskeysyncd Service
ipa: INFO: The ipactl command was successful
```
And bind fails with the following:
```
[root@example /]# systemctl status named-pkcs11 -l
* named-pkcs11.service - Berkeley Internet Name Domain (DNS) with native PKCS#11
   Loaded: loaded (/usr/lib/systemd/system/named-pkcs11.service; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-05-15 21:57:05 CEST; 9s ago
  Process: 422 ExecStart=/usr/sbin/named-pkcs11 -u named $OPTIONS (code=exited, status=1/FAILURE)
  Process: 420 ExecStartPre=/bin/bash -c if [ ! "$DISABLE_ZONE_CHECKING" == "yes" ]; then /usr/sbin/named-checkconf -z /etc/named.conf; else echo "Checking of zone files is disabled"; fi (code=exited, status=0/S
UCCESS)

May 15 21:56:25 example.com named-pkcs11[428]: option 'serial_autoincrement' is not supported, ignoring
May 15 21:56:45 example.com named-pkcs11[428]: GSSAPI client step 1
May 15 21:56:45 example.com named-pkcs11[428]: GSSAPI client step 1
May 15 21:57:05 example.com named-pkcs11[428]: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server ldap/example.com@EXAMPLE.COM not found in Kerberos database)
May 15 21:57:05 example.com named-pkcs11[428]: LDAP error: Local error: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server ldap/example.com@EXAMPLE.COM not found in Kerberos database): bind to LDAP server failed
May 15 21:57:05 example.com named-pkcs11[428]: couldn't establish connection in LDAP connection pool: failure
May 15 21:57:05 example.com systemd[1]: named-pkcs11.service: Control process exited, code=exited status=1
May 15 21:57:05 example.com systemd[1]: Failed to start Berkeley Internet Name Domain (DNS) with native PKCS#11.
May 15 21:57:05 example.com systemd[1]: named-pkcs11.service: Unit entered failed state.
May 15 21:57:05 example.com systemd[1]: named-pkcs11.service: Failed with result 'exit-code'.
```
All other services look fine to me.
```
[root@example /]# netstat -tulpn | wc -l
26
[root@example /]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:749             0.0.0.0:*               LISTEN      725/kadmind
tcp        0      0 0.0.0.0:464             0.0.0.0:*               LISTEN      725/kadmind
tcp        0      0 0.0.0.0:88              0.0.0.0:*               LISTEN      717/krb5kdc
tcp6       0      0 :::8443                 :::*                    LISTEN      -
tcp6       0      0 :::443                  :::*                    LISTEN      761/httpd
tcp6       0      0 :::636                  :::*                    LISTEN      -
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN      -
tcp6       0      0 :::389                  :::*                    LISTEN      -
tcp6       0      0 127.0.0.1:8009          :::*                    LISTEN      -
tcp6       0      0 :::749                  :::*                    LISTEN      725/kadmind
tcp6       0      0 :::8080                 :::*                    LISTEN      -
tcp6       0      0 :::464                  :::*                    LISTEN      725/kadmind
tcp6       0      0 :::80                   :::*                    LISTEN      761/httpd
tcp6       0      0 :::88                   :::*                    LISTEN      717/krb5kdc
udp        0      0 0.0.0.0:88              0.0.0.0:*                           717/krb5kdc
udp        0      0 192.168.136.4:123       0.0.0.0:*                           -
udp        0      0 127.0.0.1:123           0.0.0.0:*                           -
udp        0      0 0.0.0.0:123             0.0.0.0:*                           -
udp        0      0 0.0.0.0:464             0.0.0.0:*                           725/kadmind
udp6       0      0 :::88                   :::*                                717/krb5kdc
udp6       0      0 fe80::42:c0ff:fea8::123 :::*                                -
udp6       0      0 ::1:123                 :::*                                -
udp6       0      0 :::123                  :::*                                -
udp6       0      0 :::464                  :::*                                725/kadmind
```

**Comment by Trisooma** [comment] 2017-06-01 23:09
BUMP - Has anyone looked at this already?

**Comment by adelton** [comment] 2017-08-18 14:22
Please use `freeipa/freeipa-server:fedora-25` image instead.

**Comment by chesty** [comment] 2017-12-01 01:04
I think I'm seeing this problem too, 
the hostname was set to ipa.example.com during installation, 
but if you look at the prompt after the restart, it's [root@example /] ie the hostname is example.
If I run `hostname ipa`, then run `systemctl start ipa` it comes up OK.

**Comment by adelton** [comment] 2017-12-01 07:12
@chesty, which image is this, and how do you run the container?

**Comment by chesty** [comment] 2017-12-01 07:59
Thanks @adelton ,

I installed it with the following paste, with the command: line uncommented, ran `docker-compose up`, I'm not sure why, but I needed to run docker attach -ti blah_ipa_1 to answer the questions. 
After install it works OK, then I commented out the command: line and ran `docker-compose down` and `docker-compose up` and the hostname gets set to blah.com.au. I tried various combinations of installing with and without --hostname and a few other ways, but I couldn't get it to work. ATM i added a hostname.system to run `hostname ipa` and it works ok. 

blah.com.au exists and is in use, and when freeipa is finished being configured it will be the master for that zone. 

```yaml
version: '3.4'

services:
  ipa:
    image: freeipa/freeipa-server
    hostname: ipa
    domainname: blah.com.au
    stop_signal: RTMIN+3
#    tty: true
#    stdin_open: true
    cap_add:
      - SYS_ADMIN
      - SYS_TIME
    environment:
      - container=docker
      - IPA_SERVER_HOSTNAME=ipa.blah.com.au
      - IPA_SERVER_IP=192.168.1.50
      - DEBUG_TRACE=1
      - DEBUG_NO_EXIT=1
#    security_opt:
#      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - type: volume
        source: ipa-data
        target: /data
    networks:
      - one
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 389
        published: 389
        protocol: tcp
        mode: host
      - target: 636
        published: 636
        protocol: tcp
        mode: host
      - target: 88
        published: 88
        protocol: tcp
        mode: host
      - target: 464
        published: 464
        protocol: tcp
        mode: host
      - target: 88
        published: 88
        protocol: udp
        mode: host
      - target: 464
        published: 464
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    #command: --allow-zone-overlap --setup-dns --forwarder=8.8.8.8
volumes:
  ipa-data:
    external: true

networks:
  one:
    external: true

```

**Comment by adelton** [comment] 2017-12-01 09:01
Please try setting `IPA_SERVER_HOSTNAME`, judging by https://github.com/freeipa/freeipa-container/issues/98#issuecomment-271232555 we've added it to be able workaround issues with `docker-compose`.

**Comment by adelton** [comment] 2017-12-01 09:06
@Trisooma, checking your `docker run` parameters, that `--security-opt seccomp=unconfined` might be causing issue in latest images. It probably is not related to this issue you've reported but I thought I'd note that.

**Comment by adelton** [comment] 2017-12-01 09:07
> Please try setting environment varialbe IPA_SERVER_HOSTNAME, judging by #98 (comment) we've added it in 91eece6, to be able workaround issues with docker-compose.

Ah, you already have that set -- sorry for missing it.

**Comment by chesty** [comment] 2017-12-01 09:24
yeah, when it didn't work, and I think originally it didn't work because of systemd not working properly, I googled around and found various things to try, something things I found might not be needed, I guess - --tmpfs /run/lock isn't needed anymore? I'm not sure if target: /data needs to be target: /data:Z. so many moving parts. I'm very much a newb.

**Comment by chesty** [comment] 2017-12-03 01:26
I think half the problems I'm seeing here is blah.com.au is an existing domain in production. Possibly hostname: ipa is causing problems too, it might need to be hostname: ipa.blah.com.au and no domainname: . 
When it's starting up, I believe it's doing DNS lookups which are being answered by the existing and in production blah.com.au DNS server, not freeipa.
Other complications are ipa.blah.com.au has 3 ip addresses, an internet routeable one, a 192.168.1.50 one, and the container ip address,  172.19.0.3 atm. 
lots of moving parts.
Setting  - IPA_SERVER_HOSTNAME=ipa.blah.com.au and - IPA_SERVER_IP=192.168.1.50 doesn't seem to be the final and overriding setting, it still does DNS lookups answered by the production dns server/zone, and if things don't match ipa reconfigures itself.
I'll work it out and post an update.

**Comment by adelton** [comment] 2017-12-04 07:17
Thanks for that investigation and theory. If this is the case, you should be able to start by specifying (some bogus) DNS server for the container which does not resolve that existing production domain. Would that make things work?

**Comment by chesty** [comment] 2017-12-04 09:08
Yes, I have a freeipa replica, I run a systemd service unit (I'm not sure of the correct term) that runs before ipa to change /etc/resolv.conf from 127.0.0.11 to point to the freeipa replica and change the hostname to ipa.blah.com.au it's reliable now.
I'm wondering though, years ago I thought I learned a hostname was (eg) ipa and a fully qualified domain name was (eg) ipa.blah.com.au. /etc/hostname would be ipa and /etc/hosts would have an entry that set hostname -f to ipa.blah.com.au.
but some people seem to say the hostname is ipa.blah.com.au. and hostname returns ipa.blah.com.au and hostname -f returns the same.

**Comment by Trisooma** [comment] 2017-12-04 20:29
Since my wholeFreeIPA experience suffered from this error, I decided to run FreeIPA w/o DNS server and that 'fixed' my specific problem.

@chesty that example thing might be a by-product of me trying to hide my domain name :-)

**Comment by chesty** [comment] 2017-12-04 22:41
@Trisooma i understood your real domain name isn't example.com, my real domain name isn't blah.com.au.

just adding a note to no one in particular:
in `/usr/sbin/ipa-server-configure-first` in `function update_server_ip_address () {` there is a line `CURRENT_IP=$( dig +short -t A $HOSTNAME )` later there is
```bash
(
                echo "update add $HOSTNAME 180 A $MY_IP"
                echo "update delete $HOSTNAME A $CURRENT_IP"
                echo "send"
                echo "quit"
        ) | nsupdate -g
```

We're making the assumption $CURRENT_IP has 1 IP address, but due to misconfigurations, it might have 2 or more IP addresses. This is one problem I was seeing. Could you consider a for loop here?

This is one problem I was having, also the dig was querying the in production domain name which had at one time the external IP address so I could get a letsencrypt SSL certificate.

**Comment by adelton** [comment] 2017-12-07 14:34
> We're making the assumption $CURRENT_IP has 1 IP address, but due to misconfigurations, it might have 2 or more IP addresses. Could you consider a for loop here?

I've filed https://github.com/freeipa/freeipa-container/pull/173 for that.

**Comment by adelton** [comment] 2017-12-07 14:37
@stlaz, @Tiboris, could we have some tests run with existing domains now that we know that this is the main culprit, to properly iron out all the rough edges? Could you check if it's specific to containerized setups?

Of course, running the container with `--dns 1.2.3.4` with bogus DNS server IPA address (or perhaps with 127.0.0.2) might also be the solution if we are not able to handle the case in the code ... in which case adding a note to README might be the best course of action.

**Comment by chesty** [comment] 2017-12-10 03:20
For me, and I believe this bug, the main problem is --hostname=ipa.blah.com.au not working. Without it the hostname gets set to blah.com.au, with it the hostnamectl command fails, exits 1 and the container stops.

**Comment by chesty** [comment] 2017-12-10 16:24
this looks like the commit that causes my issues and this bug
https://github.com/freeipa/freeipa-container/commit/e52b5e6fb3d3ab4246c5e0c3a78fe6c8541a3d1b#diff-06f25d335b1c124314ae262c81b1af02
I don't understand why everyone isn't seeing it?
I guess it's to do with SYS_ADMIN, I can't start the container without it, I'm not sure why other people can.

**Comment by adelton** [comment] 2017-12-11 08:45
> Oh, domainname symlinks to hostname, hostname must check if argv[0] == domainname and if true, change the domainname, else change the hostname,
> because of the wrapper, now argv[0] == domainname.orig so domainname now changes the hostname

But in https://github.com/freeipa/freeipa-container/blob/master/Dockerfile.fedora-25#L34 we do

```
mv /usr/bin/domainname /usr/bin/domainname.orig
```

so we move that symlink aside. And replace it with

```
ADD hostnamectl-wrapper /usr/bin/domainname
```

So now you should have the wrapper which will refuse to run if you don't have SYS_ADMIN.

> I don't understand why everyone isn't seeing it?
> I guess it's to do with SYS_ADMIN, I can't start the container without it, I'm not sure why other people can.

This explains why nobody else is seeing the problem -- noone else probably runs the container with SYS_ADMIN, so this code-path is never hit. What do you mean "can't start the container without it"? What error message do you get?

**Comment by chesty** [comment] 2017-12-11 09:44
Without SYS_ADMIN I get 
```
ipa_1  | Failed to determine whether /sys is a mount point: Operation not permitted
```
docker changes in 1.12 and higher require SYS_ADMIN for systemd to work
https://github.com/moby/moby/issues/25290

Man, this was tricky to debug while trying to learn multiple things at the same time, so many moving parts, I think that's the third time I've said that here.

I agree changing the wrapper to use -y is much cleaner, what should I do with my PR?

**Comment by adelton** [comment] 2017-12-11 09:59
If you use RHEL, CentOS, or Fedora and the `docker` packages that come with those, plus their dependencies (`container-selinux`, etc), no SYS_ADMIN is needed to run systemd in container.

**Comment by chesty** [comment] 2017-12-11 10:14
ok. I think Docker are going to have to change their slogan "Docker - Build, Ship, and Run Any App, Anywhere" So 1.12 or higher on fedora doesn't require SYS_ADMIN? ie it's not because they are still on 1.11?

**Comment by adelton** [comment] 2017-12-11 10:41
My Fedora 26 has docker-1.13.1-22.gitb5e3294.fc26.x86_64.

**Comment by chesty** [comment] 2017-12-11 11:21
Do you know what changes were made to remove the SYS_ADMIN requirement? 

I guess it can be documented that SYS_ADMIN isn't needed on RHEL/CentOS/Fedora, it is needed on Debian and Ubuntu and possibly others if docker version >= 1.12

**Comment by adelton** [comment] 2017-12-11 11:32
There have been many weird interactions. For starters, there's not one "systemd" in the container -- systemd changes very fast so checking the latest versions might help.

Other than that, following up the code path around `path_is_mount_point` in systemd source might give some clue about the failure you are seeing.

Oh, and RHEL / CentOS / Fedora also include `oci-systemd-hook` even if I don't think it does anything to `/sys` specifically.

**Comment by adelton** [comment] 2017-12-11 11:35
Also, some trivial checks like

```
# docker run --rm -ti fedora:25 mount | grep ' /sys '
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime,seclabel)
```

on Fedora and on other OSes might give some clue about the difference in the container setup that systemd then sees when run.

**Comment by chesty** [comment] 2017-12-11 19:55
Thanks. I ran that on ubuntu and it looks the same, I think it's apparmor and or cgroup on the host that interferes with systemd. 
does --hostname=ipa.blah.com.au work on fedora?
It doesn't on ubuntu.
```bash
root@de54d1db59a0:/# hostnamectl set-hostname hi
Failed to create bus connection: No such file or directory
root@de54d1db59a0:/# hostnamectl --static set-hostname hi
Failed to create bus connection: No such file or directory
root@de54d1db59a0:/# echo hi > h
root@de54d1db59a0:/# mv h /etc/hostname
mv: cannot move 'h' to '/etc/hostname': Device or resource busy
root@de54d1db59a0:/# echo hi > /etc/hostname
root@de54d1db59a0:/# 
```

**Comment by adelton** [comment] 2017-12-12 09:58
The point is -- we don't care about the hostname within the container at all:

```
$ docker run -e IPA_SERVER_HOSTNAME=ipa.example.test --rm -ti freeipa/freeipa-server:fedora-25 --realm=EXAMPLE.TEST --ds-password=The-directory-server-password --admin-password=The-admin-password -U
systemd 231 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization docker.
Detected architecture x86-64.
Set hostname to <85745750dcf7>.
Failed to install release agent, ignoring: Read-only file system
Tue Dec 12 09:45:34 UTC 2017 /usr/sbin/ipa-server-configure-first 

The log file for this installation can be found in /var/log/ipaserver-install.log
==============================================================================
This program will set up the FreeIPA Server.

This includes:
  * Configure a stand-alone CA (dogtag) for certificate management
  * Configure the Network Time Daemon (ntpd)
  * Create and configure an instance of Directory Server
  * Create and configure a Kerberos Key Distribution Center (KDC)
  * Configure Apache (httpd)

The domain name has been determined based on the host name.


The IPA Master Server will be configured with:
Hostname:       ipa.example.test
IP address(es): 172.17.0.2
Domain name:    example.test
Realm name:     EXAMPLE.TEST

Configuring NTP daemon (ntpd)
  [1/4]: stopping ntpd
  [2/4]: writing configuration
[...]
Client configuration complete.

==============================================================================
Setup complete

Next steps:
	1. You must make sure these network ports are open:
		TCP Ports:
		  * 80, 443: HTTP/HTTPS
		  * 389, 636: LDAP/LDAPS
		  * 88, 464: kerberos
		UDP Ports:
		  * 88, 464: kerberos
		  * 123: ntp

	2. You can now obtain a kerberos ticket using the command: 'kinit admin'
	   This ticket will allow you to use the IPA tools (e.g., ipa user-add)
	   and the web user interface.

Be sure to back up the CA certificates stored in /root/cacert.p12
These files are required to create replicas. The password for these
files is the Directory Manager password
FreeIPA server does not run DNS server, skipping update-self-ip-address.
Created symlink /etc/systemd/system/container-ipa.target.wants/ipa-server-update-self-ip-address.service → /usr/lib/systemd/system/ipa-server-update-self-ip-address.service.
Created symlink /etc/systemd/system/container-ipa.target.wants/ipa-server-upgrade.service → /usr/lib/systemd/system/ipa-server-upgrade.service.
Failed to disable unit: Not a directory
FreeIPA server configured.
```

Yes, for everyone's sanity, it it useful to use the `-h` option and set the hostname accordingly to match what the FreeIPA software works with internally, but it's not really necessary and you can use `IPA_SERVER_HOSTNAME` just fine.

So, SYS_ADMIN is not needed to set the hostname.

It seems to bee needed for that `Failed to determine whether /sys is a mount point` issue on Ubuntu. Can you disable AppArmor to see it that's the culprit? Or in general ask Ubuntu maintainers to make systemd runnable under Ubuntu's docker without SYS_ADMIN, to bring it up par with Fedora? It might be useful to use ubuntu image with ubuntu systemd for the investigation to make sure the problem isn't related to something cross-OS-y (Ubuntu on host, Fedora with its systemd in container).

**Comment by adelton** [comment] 2017-12-13 13:37
The `domainname.orig` issue fix is now tracked in https://github.com/freeipa/freeipa-container/pull/180.

**Comment by stlaz** [comment] 2018-01-08 07:40
@chesty Since some of the issues mentioned in this thread were fixed, did you manage to proceed any further?

**Comment by chesty** [comment] 2018-01-08 08:46
Yes. Thanks.
https://github.com/freeipa/freeipa-container/pull/180 fixed "Services do not come up after restarting container"

**Comment by adelton** [comment] 2018-01-12 09:58
Thanks for reporting back. Let me close this issue then.

**Closed by adelton** 2018-01-12 09:58 UTC
