### ISSUE TITLE
Installation fails on kubernetes

### ISSUE THREAD

**Issue by mmacfadden** [freeipa/freeipa-container#172] opened 2017-12-06 14:09 UTC
We are having trouble getting FreeIPA up and running in Kubernetes. We are getting the below error. I will try to add some configuration information for k8s below shortly, but wondered if anyone had seen this issue before.

```
ue Dec  5 02:27:19 UTC 2017 /usr/sbin/ipa-server-configure-first 

The log file for this installation can be found in /var/log/ipaserver-install.log
==============================================================================
This program will set up the FreeIPA Server.

This includes:
  * Configure a stand-alone CA (dogtag) for certificate management
  * Configure the Network Time Daemon (ntpd)
  * Create and configure an instance of Directory Server
  * Create and configure a Kerberos Key Distribution Center (KDC)
  * Configure Apache (httpd)


The IPA Master Server will be configured with:
Hostname:       ipa-0.ipa.default.svc.cluster.local
IP address(es): 100.96.11.81
Domain name:    example.tech
Realm name:     example.tech

Configuring NTP daemon (ntpd)
  [1/4]: stopping ntpd
  [2/4]: writing configuration
  [3/4]: configuring ntpd to start on boot
  [4/4]: starting ntpd
Done configuring NTP daemon (ntpd).
Configuring directory server (dirsrv). Estimated time: 1 minute
  [1/47]: creating directory server user
  [2/47]: creating directory server instance
  [3/47]: updating configuration in dse.ldif
  [4/47]: restarting directory server
  [5/47]: adding default schema
  [6/47]: enabling memberof plugin
  [7/47]: enabling winsync plugin
  [8/47]: configuring replication version plugin
  [9/47]: enabling IPA enrollment plugin
  [10/47]: enabling ldapi
  [11/47]: configuring uniqueness plugin
  [12/47]: configuring uuid plugin
  [13/47]: configuring modrdn plugin
  [14/47]: configuring DNS plugin
  [15/47]: enabling entryUSN plugin
  [16/47]: configuring lockout plugin
  [17/47]: configuring topology plugin
  [18/47]: creating indices
  [19/47]: enabling referential integrity plugin
  [20/47]: configuring certmap.conf
  [21/47]: configure autobind for root
  [22/47]: configure new location for managed entries
  [23/47]: configure dirsrv ccache
  [24/47]: enabling SASL mapping fallback
  [25/47]: restarting directory server
  [26/47]: adding sasl mappings to the directory
  [27/47]: adding default layout
  [28/47]: adding delegation layout
  [29/47]: creating container for managed entries
  [30/47]: configuring user private groups
  [31/47]: configuring netgroups from hostgroups
  [32/47]: creating default Sudo bind user
  [33/47]: creating default Auto Member layout
  [34/47]: adding range check plugin
  [35/47]: creating default HBAC rule allow_all
  [36/47]: adding sasl mappings to the directory
  [37/47]: adding entries for topology management
  [38/47]: initializing group membership
  [39/47]: adding master entry
  [40/47]: initializing domain level
  [41/47]: configuring Posix uid/gid generation
  [42/47]: adding replication acis
  [43/47]: enabling compatibility plugin
  [44/47]: activating sidgen plugin
  [45/47]: activating extdom plugin
  [46/47]: tuning directory server
  [47/47]: configuring directory to start on boot
Done configuring directory server (dirsrv).
Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes 30 seconds
  [1/31]: creating certificate server user
  [2/31]: configuring certificate server instance
  [3/31]: stopping certificate server instance to update CS.cfg
  [4/31]: backing up CS.cfg
  [5/31]: disabling nonces
  [6/31]: set up CRL publishing
  [7/31]: enable PKIX certificate path discovery and validation
  [8/31]: starting certificate server instance
  [9/31]: creating RA agent certificate database
  [10/31]: importing CA chain to RA certificate database
  [11/31]: fixing RA database permissions
  [12/31]: setting up signing cert profile
  [13/31]: setting audit signing renewal to 2 years
  [14/31]: restarting certificate server
  [15/31]: requesting RA certificate from CA
  [16/31]: issuing RA agent certificate
  [17/31]: adding RA agent as a trusted user
  [18/31]: authorizing RA to modify profiles
  [19/31]: authorizing RA to manage lightweight CAs
  [20/31]: Ensure lightweight CAs container exists
  [21/31]: configure certmonger for renewals
  [22/31]: configure certificate renewals
  [error] DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
FreeIPA server configuration failed.
```

**Comment by mmacfadden** [comment] 2017-12-07 05:51
Here is a representative configuration.

```
apiVersion: v1
kind: Service
metadata:
  name: ipa
  namespace: dev
  labels:
    role: ipa
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    name: http
  selector:
    role: ipa
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: ipa
  namespace: dev
  labels:
    name: ipa
    role: ipa
spec:
  serviceName: ipa
  replicas: 1
  selector:
    matchLabels:
      role: ipa
  template:
    metadata:
      labels:
        role: ipa
    spec:
      containers:
        - name: ipa
          image: freeipa/freeipa-server:latest
          imagePullPolicy: Always
          args:
            - --hostname=ipa-0.ipa.dev.svc.cluster.local
            - --domain=dev.svc.cluster.local
            - --realm=example.test
            - --ds-password=password
            - --admin-password=password
            - --setup-dns
            - --forwarder=8.8.8.8
            - --forwarder=8.8.4.4
            - --unattended
          ports:
            - containerPort: 53
            - containerPort: 80
            - containerPort: 443
            - containerPort: 389
            - containerPort: 636
            - containerPort: 88
            - containerPort: 464
            - containerPort: 123
            - containerPort: 7389
            - containerPort: 9443
            - containerPort: 9444
            - containerPort: 9445
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /sys/fs/cgroup
              name: cgroups
              readOnly: true
            - mountPath: /run
              name: run
            - mountPath: /run/systemd
              name: run-sysd
            - mountPath: /tmp
              name: tmp
          resources:
            requests:
              memory: "750Mi"
              cpu: "1000m"
            limits:
              memory: "3000Mi"
              cpu: "2000m"
      volumes:
      - name: data
        emptyDir:
          medium: Memory
      - hostPath:
          path: /sys/fs/cgroup
        name: cgroups
      - emptyDir:
          medium: Memory
        name: run
      - emptyDir:
          medium: Memory
        name: run-sysd
      - emptyDir:
          medium: Memory
        name: tmp
```

**Comment by mmacfadden** [comment] 2017-12-07 06:10
I also tried with the centos-7 tag.

**Comment by chesty** [comment] 2017-12-08 03:59
I think you need
```yaml
    cap_add:
      - SYS_ADMIN
```
But I have a problem with using --hostname= args in docker-compose, too I tried taking it out and using 
```yaml
    environment:
      - IPA_SERVER_HOSTNAME=ipa.blah.com.au
      - IPA_SERVER_IP=192.168.1.50
```
Where IPA_SERVER_IP is the ip address clients will use to connect to ipa, which might be different to the container ip address. 
It's still not perfect, it installs, but `hostname` returns blah.com.au and causes problems on restart, so I run a systemd unit to set the hostname before ipa starts to ipa.blah.com.au

I haven't managed to do an unattended replica install yet. It looks like the replica install script calls the client install script without the principle set. I'm still testing and documenting.

**Comment by mmacfadden** [comment] 2017-12-08 16:41
So I got past the problem above. It turns out that it was actually the fact that the realm and domain were not the same. The installer really did not like that.

The new issue though is that the host name seems to need to be set to the A-Record for the node INSIDE the cluster. So something like this:

`ipa-0.ipa.default.svc.cluster.local`

The problem then, we have an ingress that maps the CNAME "ipa.mydomain.com" to point to the ingress. When you hit this with HTTPS IPA immediately issues a redirect to "ipa-0.ipa.default.svc.cluster.local" which is not a publicly routable name as far as your web browser is concerned.

**Comment by chesty** [comment] 2017-12-09 03:13
Sweet, did you know you can control what IP address the A record gets set to with the env variable IPA_SERVER_IP=192.168.1.50 and or the args --ip-address=192.168.1.50 ? I wasn't sure from what you said whether you were setting the IP but it was causing problems or what. 

I wondered why yours worked without SYS_ADMIN, after comparing and testing I found if I add a /run/systemd tmpfs mount, I don't need SYS_ADMIN. Awesome. Cheers.

I still can't use --hostname=ipa.blah.com.au, that's next on the list to work out why.

**Comment by adelton** [comment] 2017-12-11 09:36
> I think you need
> 
>     cap_add:
>       - SYS_ADMIN

We've established in https://github.com/freeipa/freeipa-container/issues/135 that adding the SYS_ADMIN capability will actually cause some of the hostname/domainname mixup. Yes, it needs to be fixed but I don't think enabling it is the right way to go in general.

**Comment by mmacfadden** [comment] 2017-12-13 04:02
I agree. I am still working on getting this completely working. I am close. Also it seems that some of the recommendations above were coming from a docker compose set up vs. kubernetes.

**Comment by mikeatm** [comment] 2018-04-25 20:55
@mmacfadden  
did you get this done successfully? anyone else with a sample ks8 config?

**Comment by adelton** [comment] 2018-04-26 07:50
The following YAML should get you started, it works for me with Kubernetes master branch:

```
apiVersion: v1
kind: Secret
metadata:
  name: freeipa-server-password
stringData:
  admin.password: Secret123
---
apiVersion: v1
kind: Service
metadata:
  name: freeipa-server-service
spec:
  selector:
    app: freeipa-server
  clusterIP: 10.254.0.100
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: kerberos-tcp
    port: 88
    protocol: TCP
    targetPort: 88
  - name: kerberos-udp
    port: 88
    protocol: UDP
    targetPort: 88
---
apiVersion: v1
kind: Pod
metadata:
  name: freeipa-server
  labels:
    app: freeipa-server
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
spec:
  restartPolicy: Never
  containers:
  - name: freeipa-server
    image: freeipa/freeipa-server:fedora-26
    volumeMounts:
    - name: freeipa-server-data
      mountPath: /data
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 443
      protocol: TCP
    - containerPort: 53
      protocol: UDP
    - containerPort: 88
      protocol: TCP
    - containerPort: 88
      protocol: UDP
    env:
    - name: IPA_SERVER_HOSTNAME
      value: ipa.example.test
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: freeipa-server-password
          key: admin.password
    - name: IPA_SERVER_INSTALL_OPTS
      value: "-U -r EXAMPLE.TEST --setup-dns --no-forwarders --no-ntp"
    readinessProbe:
      exec:
        command: [ "/usr/bin/systemctl", "status", "ipa" ]
      initialDelaySeconds: 60
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  volumes:
  - name: freeipa-server-data
    hostPath:
      path: /opt/freeipa-server
```

**Comment by mikeatm** [comment] 2018-04-26 12:10
@adelton  i get a segfault.  and systemd reports this error:

```
systemctl  status ipa 
Failed to connect to bus: No such file or directory
```
There is a core file in the base of the container filesystem, and the log files are quite empty, not idea how to  debug that.

**Comment by adelton** [comment] 2018-04-26 13:58
Segfault of what, where?

For the record, for me things work on Fedora 27 host.

**Comment by mmacfadden** [comment] 2018-04-26 16:47
@mikeatm I never did get it working, but there has been much work on both this and k8s since I last tried.

**Comment by mikeatm** [comment] 2018-04-26 20:58
@adelton 
I have no idea either, but there is a  "core" file at the root of the freeipa container when i  deploy , so something segfaulted in the container but i have no way of knowing what.

**Comment by adelton** [comment] 2018-04-27 06:57
Using `gdb` on the `core` file should give some clues.

**Comment by howels** [comment] 2018-07-17 10:16
I am having issues running on Kubernetes using an default Kubespray install built latest on CentOS 7 images.  Container seems unable to enact the seccomp policy and systemd isn't working "Failed to connect to bus: No such file or directory"
The spec is attached, was working on a slightly older version of Kubernetes built on CentOS Atomic but it's failing on 1.10 at present.  Any particular seccomp changes needed with latest Kubernetes?
[freeipa.yml.txt](https://github.com/freeipa/freeipa-container/files/2201206/freeipa.yml.txt)

**Comment by adelton** [comment] 2018-07-17 15:13
In my setups, I use annotation on the Pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: freeipa-server
  labels:
    app: freeipa-server
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
spec:
  containers:
[...]
```

**Comment by howels** [comment] 2018-07-17 16:59
I've tried the pod-level annotation, the result is the same (the pod level annotation is the same result but without the use of a deployment object). It works on Atomic (cgroup-driver=cgroupfs) but fails on CentOS server (cgroup-driver=systemd) what is your underlying OS and how is kubelet configured?

**Comment by howels** [comment] 2018-07-18 12:56
Update: Replicating the Docker and Kubernetes cgroup-driver and seccomp setup on both installs changed nothing, the install still fails on CentOS; whether using a single pod example as posted above or using a deployment. Systemctl is unable to connect to the bus and hence cannot start services or pass the health check. I am continuing to test other options.

Can anyone show a working config using CentOS or RHEL as the kubernetes host?

**Comment by adelton** [comment] 2018-07-19 15:23
Can you reproduce the problem outside of Kubernetes, with just docker? I don't have Kubernetes on RHEL 7 specifically but I do run FreeIPA on containers on RHEL 7.

**Comment by howels** [comment] 2018-07-31 15:04
No, this is a Kubernetes issue only. We are working around this by using Docker. CentOS 7 is our current testing platform and that is raising the issues. Seems that the use of systemd is the crux, if it is possible to restructure following best practice and put each process inside it's own container inside the same Pod in Kubernetes then we would not need to mess with systemd and unusual container privileges.

**Comment by adelton** [comment] 2018-07-31 15:43
@howels, what docker do you use on that CentOS? Do you have `oci-systemd-hook` installed? You might be hitting a problem that `/tmp` and `/run` are not mounted as `tmpfs` ...

**Comment by adelton** [comment] 2018-07-31 15:46
@howels, in addition to what @abbra has said, if you have a patch against FreeIPA which will allow easy installation of individual daemons split into multiple containers while handling all the corner cases, I'll be happy to test it and I'm sure the FreeIPA team will at least consider reviewing it.

**Comment by adelton** [comment] 2018-08-11 19:12
It seems we've lost the traction here, closing.

**Closed by adelton** 2018-08-11 19:12 UTC

**Comment by howels** [comment] 2018-08-11 20:09
We moved to docker, I guessed that systemd is quite central and so forklifting into K8S doesn't make sense until the services are properly abstracted into pods. Still a great product but dbus etc means we will keep this out of Kubernetes for now.

**Comment by adelton** [comment] 2018-08-11 20:38
OK, thanks for the note.

**Comment by briantopping** [comment] 2018-09-10 00:13
@adelton Have you updated the yaml you provided in 
https://github.com/freeipa/freeipa-container/issues/172#issuecomment-384547078 at all lately? I have deployed it with 1.11 on Ceph for PVC, but it doesn't get too far:
```
[root@centos01 kube-cfg]# kc logs freeipa-server -f
Sun Sep  9 23:37:31 UTC 2018 /usr/sbin/ipa-server-configure-first 
The log file for this installation can be found in /var/log/ipaserver-install.log
==============================================================================
This program will set up the FreeIPA Server.
This includes:
  * Configure a stand-alone CA (dogtag) for certificate management
  * Create and configure an instance of Directory Server
  * Create and configure a Kerberos Key Distribution Center (KDC)
  * Configure Apache (httpd)
  * Configure DNS (bind)
  * Configure the KDC to enable PKINIT
Excluded by options:
  * Configure the Network Time Daemon (ntpd)
Warning: skipping DNS resolution of host ipa.example.test
The domain name has been determined based on the host name.
Checking DNS domain example.test., please wait ...
The IPA Master Server will be configured with:
Hostname:       ipa.example.test
IP address(es): 10.16.0.12
Domain name:    example.test
Realm name:     EXAMPLE.TEST
BIND DNS server will be configured to serve IPA domain with:
Forwarders:       No forwarders
Forward policy:   only
Reverse zone(s):  No reverse zone
Configuring directory server (dirsrv). Estimated time: 30 seconds
  [1/44]: creating directory server instance
  [error] RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmpjr0_1p00' returned non-zero exit status 1.
```

Grateful for any feedback you may have! :) :) :)
