### ISSUE TITLE
Replication healthchek failed after upgrade to centos8-4.9.2

### ISSUE THREAD

**Issue by alexandrovas** [freeipa/freeipa-container#409] opened 2021-07-01 09:16 UTC
Hello!
I have errors after upgrade to centos8-4.9.2:
```
ipa-healthcheck --failures-only
...
{
    "source": "ipahealthcheck.ds.replication",
    "check": "ReplicationCheck",
    "result": "ERROR",
    "uuid": "194574b9-2394-45dc-aaea-abe992c6f2c3",
    "when": "20210701090308Z",
    "duration": "0.171359",
    "kw": {
      "key": "DSREPLLE0003",
      "items": [
        "Replication",
        "Agreement"
      ],
      "msg": "The replication agreement (metoipa01.prod-ins2.pcbl.local) under \"dc=pcbl,dc=local\" is not in synchronization.\nStatus message: error (1) can't acquire busy replica (unable to acquire replica: the replica is currently being updated by another supplier.)"
    }
  }
...
```

The error is not permanent, it appears and disappears on all replicas in my topology. I have script that starts by cron every 5 minutes and it parses ipa-healthcheck output.

My docker-compose.yml:

```yml
version: "3.5"

services:
  freeipa:
    image: freeipa/freeipa-server:centos-8-4.9.2
    container_name: freeipa
    restart: always
    network_mode: host
    hostname: ipa01.prod.pcbl.local
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./data:/data:Z
      - ./conf/ipa-options-ext.conf:/etc/named/ipa-options-ext.conf
      - ./conf/ipa-ext.conf:/etc/named/ipa-ext.conf
      - ./conf/rpz.zone:/etc/named/rpz/rpz.zone
      - ./conf/ipa_healthcheck:/etc/cron.d/ipa_healthcheck
      - ./conf/pki-log-clean:/etc/cron.d/pki-log-clean
      - ./conf/scripts:/scripts:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev/urandom:/dev/random:ro
      - /opt/node_exporter/metrics/freeipa.prom:/metrics/freeipa.prom
      - ./conf/chrony.conf:/etc/chrony.conf
    cap_add:
      - SYS_TIME
    tmpfs:
      - /run
      - /tmp
    environment:
      TZ: Europe/Moscow
      IPA_SERVER_HOSTNAME: ipa01.prod.pcbl.local
      IPA_SERVER_IP: 10.72.4.20
    extra_hosts:
      - "ipa01.prod.pcbl.local:10.72.4.20"
      - "ipa01:10.72.4.20"
```

In /var/log/dirsrv/slapd-PCBL-LOCAL/errors I see such messages:
```
[01/Jul/2021:08:59:34.206569590 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "fqdn=ed-gredis-01.prod.pcbl.local,cn=computers,cn=accounts,dc=pcbl,dc=local" (op=0x7f8e06900e00 idx_pl=0) => op not changed in PL
[01/Jul/2021:09:00:11.090972399 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "fqdn=ed-glob-db-03.prod.pcbl.local,cn=computers,cn=accounts,dc=pcbl,dc=local" (op=0x7f8e17224000 idx_pl=0) => op not changed in PL
[01/Jul/2021:09:00:11.161777148 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "fqdn=mgmt-efk-04.prod.pcbl.local,cn=computers,cn=accounts,dc=pcbl,dc=local" (op=0x7f8e30a24800 idx_pl=0) => op not changed in PL
[01/Jul/2021:09:00:14.083754313 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "fqdn=ed-mng-db-02.prod.pcbl.local,cn=computers,cn=accounts,dc=pcbl,dc=local" (op=0x7f8e0ac14e00 idx_pl=0) => op not changed in PL
[01/Jul/2021:09:10:22.097113649 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "dc=pcbl,dc=local" (op=0x7f8e18024c00 idx_pl=0) => op not changed in PL
```

This messages appears constantly for different LDAP targets.

**Comment by adelton** [comment] 2021-07-01 11:15
I see that "sync_update_persist_betxn_pre_op - DB retried operation targets ... op not changed in PL" as a new (?) patch in https://git.centos.org/rpms/389-ds-base/c/3280a940515d45d902a2b5caa7720107d4f3acac?branch=c8-stream-1.4. So this seems like some new logic in RHEL 8.4 / CentOS 8.4.2105 and it looks like not something related to the containerization of FreeIPA.

Ideally, if you were able to reproduce this issue outside of containers on CentOS 8 Stream, you should be able to file this as a bug in bugzilla.redhat.com. (@abbra, do I understand the RHEL / CentOS Stream relationship and bug filing process right?)

**Comment by abbra** [comment] 2021-07-01 11:20
yes, filing bug against 389-ds-base is the way. I think this one already has a bug, though. E.g. https://bugzilla.redhat.com/show_bug.cgi?id=1930188 should have fixed it.

**Comment by alexandrovas** [comment] 2021-07-01 12:06
However I dont have the ability to reproduce this bug in RHEL or CentOS, because I use only Ubuntu OS in my infrastructure.

**Comment by adelton** [comment] 2021-07-01 12:36
Thanks for the pointer to the bugzilla, @abbra. The errata https://access.redhat.com/errata/RHBA-2021:1835 lists 389-ds-base-1.4.3.16-13.module+el8.4.0+10307+74bbfb4e.src.rpm as the package having the fix, while http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/ has only 389-ds-base-1.4.3.16-13.module_el8.4.0+804+98b1df0d.x86_64.rpm (804 < 10307).

So I'd close this as known issue https://bugzilla.redhat.com/show_bug.cgi?id=1930188, where hopefully the fixed package will get to CentOS eventually.

**Closed by adelton** 2021-07-01 12:36 UTC

**Comment by abbra** [comment] 2021-07-01 12:50
CentOS Stream has different builds in their modular build system but it attempts to keep the same NVR for the packages. So with regards to 389-ds-base-1.4.3.16-13, it is the same package in both RHEL and CentOS Stream, just built in different build systems.

**Comment by alexandrovas** [comment] 2021-07-01 12:57
@abbra It turns out that this fix does not fix the error described above?
In my freeipa-container I have latest package: 1.4.3.16-13.module_el8.4.0+804+98b1df0d

**Comment by abbra** [comment] 2021-07-01 12:59
I don't have an answer for that. If you can reproduce on RHEL 8/CentOS 8 Stream, feel free to file a bug against 389-ds-base.
