### ISSUE TITLE
Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY

### ISSUE THREAD

**Issue by JoyceBabu** [freeipa/freeipa-container#280] opened 2019-08-14 11:35 UTC
I was able to start the installation after changing the hostname in docker-compose. But `ipa-adtrust-install` is now failing with the following error when creating samba config registry.

> Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY

The machine has 12GB of free RAM and enough free disk space.

```
2019-08-14T11:29:51Z DEBUG stderr=
2019-08-14T11:29:51Z DEBUG Loading StateFile from '/var/lib/ipa/sysrestore/sysrestore.state'
2019-08-14T11:29:51Z DEBUG Saving StateFile to '/var/lib/ipa/sysrestore/sysrestore.state'
2019-08-14T11:29:51Z DEBUG Starting external process
2019-08-14T11:29:51Z DEBUG args=['/bin/systemctl', 'stop', 'winbind.service']
2019-08-14T11:29:51Z DEBUG Process finished, return code=0
2019-08-14T11:29:51Z DEBUG stdout=
2019-08-14T11:29:51Z DEBUG stderr=
2019-08-14T11:29:51Z DEBUG Stop of winbind.service complete
2019-08-14T11:29:51Z DEBUG Starting external process
2019-08-14T11:29:51Z DEBUG args=['/bin/systemctl', 'stop', 'smb.service']
2019-08-14T11:29:51Z DEBUG Process finished, return code=0
2019-08-14T11:29:51Z DEBUG stdout=
2019-08-14T11:29:51Z DEBUG stderr=
2019-08-14T11:29:51Z DEBUG Stop of smb.service complete
2019-08-14T11:29:51Z DEBUG step duration: smb __stop 0.09 sec
2019-08-14T11:29:51Z DEBUG   [3/26]: creating samba domain object
2019-08-14T11:29:51Z DEBUG Samba domain object already exists
2019-08-14T11:29:51Z DEBUG step duration: smb __create_samba_domain_object 0.00 sec
2019-08-14T11:29:51Z DEBUG   [4/26]: retrieve local idmap range
2019-08-14T11:29:51Z DEBUG raw: idrange_show('ENNEXA.COM_id_range', version='2.233')
2019-08-14T11:29:51Z DEBUG idrange_show('ENNEXA.COM_id_range', rights=False, all=False, raw=False, version='2.233')
2019-08-14T11:29:51Z DEBUG step duration: smb __retrieve_local_range 0.00 sec
2019-08-14T11:29:51Z DEBUG   [5/26]: creating samba config registry
2019-08-14T11:29:51Z DEBUG Starting external process
2019-08-14T11:29:51Z DEBUG args=['/usr/bin/net', 'conf', 'import', '/tmp/tmp31gv178_']
2019-08-14T11:29:51Z DEBUG Process finished, return code=255
2019-08-14T11:29:51Z DEBUG stdout=
2019-08-14T11:29:51Z DEBUG stderr=Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY

2019-08-14T11:29:51Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ipaserver/install/service.py", line 603, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.7/site-packages/ipaserver/install/service.py", line 589, in run_step
    method()
  File "/usr/lib/python3.7/site-packages/ipaserver/install/adtrustinstance.py", line 552, in __write_smb_registry
    ipautil.run([paths.NET, "conf", "import", tmp_conf.name])
  File "/usr/lib/python3.7/site-packages/ipapython/ipautil.py", line 594, in run
    p.returncode, arg_string, output_log, error_log
ipapython.ipautil.CalledProcessError: CalledProcessError(Command ['/usr/bin/net', 'conf', 'import', '/tmp/tmp31gv178_'] returned non-zero exit status 255: 'Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY\n')

2019-08-14T11:29:51Z DEBUG   [error] CalledProcessError: CalledProcessError(Command ['/usr/bin/net', 'conf', 'import', '/tmp/tmp31gv178_'] returned non-zero exit status 255: 'Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY\n')
2019-08-14T11:29:51Z DEBUG   File "/usr/lib/python3.7/site-packages/ipaserver/install/installutils.py", line 746, in run_script
    return_value = main_function()

  File "/usr/sbin/ipa-adtrust-install", line 213, in main
    adtrust.install(True, options, fstore, api)

  File "/usr/lib/python3.7/site-packages/ipaserver/install/adtrust.py", line 420, in install
    smb.create_instance()

  File "/usr/lib/python3.7/site-packages/ipaserver/install/adtrustinstance.py", line 898, in create_instance
    self.start_creation(show_service_name=False)

  File "/usr/lib/python3.7/site-packages/ipaserver/install/service.py", line 603, in start_creation
    run_step(full_msg, method)

  File "/usr/lib/python3.7/site-packages/ipaserver/install/service.py", line 589, in run_step
    method()

  File "/usr/lib/python3.7/site-packages/ipaserver/install/adtrustinstance.py", line 552, in __write_smb_registry
    ipautil.run([paths.NET, "conf", "import", tmp_conf.name])

  File "/usr/lib/python3.7/site-packages/ipapython/ipautil.py", line 594, in run
    p.returncode, arg_string, output_log, error_log

2019-08-14T11:29:51Z DEBUG The ipa-adtrust-install command failed, exception: CalledProcessError: CalledProcessError(Command ['/usr/bin/net', 'conf', 'import', '/tmp/tmp31gv178_'] returned non-zero exit status 255: 'Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY\n')
```

**Comment by adelton** [comment] 2019-08-14 12:42
Can you check `docker stats <the-container-id>` to see if some memory limit is applied?

**Comment by JoyceBabu** [comment] 2019-08-14 14:50
`docker stats` does not show any limits

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
760fb258c88e        freeipa             0.00%               8.785MiB / 15.57GiB   0.06%               298kB / 1.79MB      134MB / 90.1kB      3
```

**Comment by adelton** [comment] 2019-08-14 15:15
Then I sadly don't know.

**Comment by JoyceBabu** [comment] 2019-08-14 23:04
I used `strace` and compared the result to the samba source.

The `net conf import` call is failing at

https://github.com/samba-team/samba/blob/d5383297f0389d01d42479b074f5e81619e03ddb/lib/util/util.c#L372

It expects `/var/lib/samba` to be a directory.

I replaced the symlink `/var/lib/samba` with the target directory `/data/var/lib/samba` and ran `ipa-atrust-install`, and it completed successfully.

**Comment by JoyceBabu** [comment] 2019-08-15 07:17
I am seeing similar error messages in `/var/log/samba/log.smbd` about `/etc/samba` too. Samba expects `/etc/samba` to be a directory.

**Comment by adelton** [comment] 2019-08-15 07:25
Nice investigation.

The should be able to patch `/var/lib/samba/` in /usr/lib/python3.7/site-packages/ipaplatform/base/paths.py, there's
```
SAMBA_DIR = "/var/lib/samba/"
```
there.

But as for `/etc/samba` -- there's
```
    SAMBA_KEYTAB = "/etc/samba/samba.keytab"
    SMB_CONF = "/etc/samba/smb.conf"
```
but not the directory itself. But maybe similar to the other keytabs, we need to use the patch which does not go "through" the symlink.

What image do you work with? I'd prepare patch against the `ipa-data-*.patch` if you'd be willing to try it.

**Comment by JoyceBabu** [comment] 2019-08-15 07:34
Sorry, I saw your response only after updating the original comment.

I am using `fedora-30`. I will test the patch, thank you.

**Comment by adelton** [comment] 2019-08-15 08:30
Thanks. Could you replace https://github.com/freeipa/freeipa-container/blob/master/patches/ipa-data-fedora-30.patch with
```
--- /usr/lib/python3.7/site-packages/ipaplatform/base/paths.py	2019-07-03 06:42:44.000000000 +0000
+++ /usr/lib/python3.7/site-packages/ipaplatform/base/paths.py	2019-08-15 08:28:29.665626731 +0000
@@ -72,14 +72,14 @@
     IPA_NSSDB_DIR = "/etc/ipa/nssdb"
     IPA_NSSDB_PWDFILE_TXT = "/etc/ipa/nssdb/pwdfile.txt"
     COMMON_KRB5_CONF_DIR = "/etc/krb5.conf.d/"
-    KRB5_CONF = "/etc/krb5.conf"
+    KRB5_CONF = "/data/etc/krb5.conf"
     KRB5_FREEIPA = COMMON_KRB5_CONF_DIR + "freeipa"
-    KRB5_KEYTAB = "/etc/krb5.keytab"
+    KRB5_KEYTAB = "/data/etc/krb5.keytab"
     LDAP_CONF = "/etc/ldap.conf"
     LIBNSS_LDAP_CONF = "/etc/libnss-ldap.conf"
     NAMED_CONF = "/etc/named.conf"
     NAMED_VAR_DIR = "/var/named"
-    NAMED_KEYTAB = "/etc/named.keytab"
+    NAMED_KEYTAB = "/data/etc/named.keytab"
     NAMED_RFC1912_ZONES = "/etc/named.rfc1912.zones"
     NAMED_ROOT_KEY = "/etc/named.root.key"
     NAMED_BINDKEYS_FILE = "/etc/named.iscdlv.key"
@@ -87,7 +87,7 @@
     NAMED_CRYPTO_POLICY_FILE = None
     NSLCD_CONF = "/etc/nslcd.conf"
     NSS_LDAP_CONF = "/etc/nss_ldap.conf"
-    NSSWITCH_CONF = "/etc/nsswitch.conf"
+    NSSWITCH_CONF = "/data/etc/nsswitch.conf"
     CHRONY_CONF = "/etc/chrony.conf"
     NTP_CONF = "/etc/ntp.conf"
     NTP_STEP_TICKERS = "/etc/ntp/step-tickers"
@@ -107,7 +107,7 @@
     PKI_TOMCAT_PASSWORD_CONF = "/etc/pki/pki-tomcat/password.conf"
     ETC_REDHAT_RELEASE = "/etc/redhat-release"
     RESOLV_CONF = "/etc/resolv.conf"
-    SAMBA_KEYTAB = "/etc/samba/samba.keytab"
+    SAMBA_KEYTAB = "/data/etc/samba/samba.keytab"
     SMB_CONF = "/etc/samba/smb.conf"
     LIMITS_CONF = "/etc/security/limits.conf"
     SSH_CONFIG_DIR = "/etc/ssh"
@@ -307,7 +307,7 @@
         "/var/lib/pki/pki-tomcat/ca/profiles/ca/caSignedLogCert.cfg")
     KRA_CS_CFG_PATH = "/var/lib/pki/pki-tomcat/conf/kra/CS.cfg"
     KRACERT_P12 = "/root/kracert.p12"
-    SAMBA_DIR = "/var/lib/samba/"
+    SAMBA_DIR = "/data/var/lib/samba/"
     SSSD_DB = "/var/lib/sss/db"
     SSSD_MC_GROUP = "/var/lib/sss/mc/group"
     SSSD_MC_PASSWD = "/var/lib/sss/mc/passwd"
```

rebuild the image and in new container try that `ipa-adtrust-install`?

**Comment by JoyceBabu** [comment] 2019-08-15 09:20
Should I replace the whole content or just the patch for `/usr/lib/python3.7/site-packages/ipaplatform/base/paths.py` in the original patch file?

Btw, is it possible to undo the `ipa-adtrust-install`?

**Comment by abbra** [comment] 2019-08-15 09:43
> Btw, is it possible to undo the ipa-adtrust-install?
No, it is not.

**Comment by adelton** [comment] 2019-08-15 09:57
Just the part of `/usr/lib/python3.7/site-packages/ipaplatform/base/paths.py`. Sorry for the confusion.

**Comment by JoyceBabu** [comment] 2019-08-15 10:05
The command was failing with the same error even after applying the patch. There was one more variable inside the same file referring to the same directory in `paths.py`. I tried changing that too, and it still did not work.

On inspecting the source again, I found that samba was loading the state directory path from `smb.conf`, so I added `state directory = /data/var/lib/samba` under the `[global]` section of `/etc/samba/smb.conf` and it worked.

Btw, you did not patch the variable `SMB_CONF `.

**Comment by JoyceBabu** [comment] 2019-08-15 10:40
Samba refuses to start since `/etc/samba` is not a directory.

**Comment by JoyceBabu** [comment] 2019-08-15 20:46
`ipa-adtrust-install` replaces the contents of `/etc/samba/smb.conf` with 

```
### Added by IPA Installer ###
[global]
debug pid = yes
config backend = registry
```

This switches the config backend from [config files to registry](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#idm360), forcing samba to discard all other configuration values specified in the file.

I was able to start `smbd`, after changing `config backend = registry` to `include = registry`, which allows configuration through config files in addition to the registry.

```
### Added by IPA Installer ###
[global]
debug pid = yes
state directory = /data/var/lib/samba
include = registry
```
The documentation for `smb.conf` recommends `config backend = registry` over `include = registry`. The ideal solution would be to set `state directory`directly  in the registry file `/var/lib/samba/registry.tdb`, under `HKLM\Software\Samba\smbconf`.

**Comment by JoyceBabu** [comment] 2019-08-15 21:09
I just realized that the configuration in `smb.conf.template` is imported into the registry during `ipa-adtrust-install` and tried adding `state directory` to the file. But `state directory` is a [forbidden parameter](https://lists.samba.org/archive/samba-technical/2013-September/095031.html), and cannot be [configured in the registry](https://github.com/samba-team/samba/blob/c4613521723e3ab9b462d75485a514ca16595226/source3/lib/smbconf/smbconf_reg.c#L60).

**Comment by adelton** [comment] 2019-09-20 10:04
@JoyceBabu, were you able to settle for some specific patch which we should carry in the repository to make `ipa-adtrust-install` work out of box? We don't have AD that we could use in Travis CI, and I don't have capacity to investigate that use case myself, so whatever you suggest is what we will have. ;-)

**Comment by JoyceBabu** [comment] 2019-09-20 12:39
I have never used AD / Samba before. I was trying to configure [windows 10 PC to use FreeIPA](https://www.rootusers.com/how-to-login-to-windows-with-a-freeipa-account/).

I settled on the `include = registry` configuration in `smb.conf`. Since `config backend = registry` ignores the configuration in `smb.conf`, and since `state directory` cannot be configured in registry, I don't know how/whether it can be changed from the default value.

Is it possible to leave `/etc/samba` as a directory, and copy its contents only?

**Comment by adelton** [comment] 2019-10-21 13:52
@abbra, if I understand the situation correctly, Samba does not like it when `/var/lib/samba` is a symlink to `/data/var/lib/samba`. Is it expected that the software fails to walk the symlink?

@JoyceBabu, in general, we tried to avoid copying (and symlinking) individual files where the whole directory should be usable as data/config directory. It caused various additional problems, with keytabs and similar. Is `/etc/samba` being symlink to `/data/etc/samba` a problem per se?

**Comment by JoyceBabu** [comment] 2019-10-21 14:33
Yes, as mentioned in a [previous comment](https://github.com/freeipa/freeipa-container/issues/280#issuecomment-521451773), samba has a check that fails when /etc/samba is not a directory. Samba requires both `/etc/samba` and `/var/lib/samba` to be directories.

For `/var/lib/samba`, I was able to work around by setting `state directory` and `cache directory` to `/data/var/lib/samba` in `smb.conf` (but this required, adding `include = registry` to `smb.con`).

For `/etc/samba`, I had to mount `$DATADIR/etc/samba` on the host to `/etc/samba` inside the container. Since `/etc/samba` is now a mount point, the init script will not replace the directory with a symlink to `/data/etc/samba` (fails with permission denied error).

**Comment by adelton** [comment] 2019-11-18 09:05
@abbra, any idea how important / critical the use of `lstat` is at https://github.com/samba-team/samba/blob/d5383297f0389d01d42479b074f5e81619e03ddb/lib/util/util.c#L367 and whether it could be replaced by `stat`?

**Comment by abbra** [comment] 2019-11-18 09:32
`directory_create_or_exist()` has pretty fundamental use inside Samba. I don't think `lstat` could be replaced by `stat` here.
I think we can modify a template created in `ipaserver/install/adtrustinstance.py:ADTRUSTInstance::__write_smb_conf` to load a file from the /usr/share/ipa/ instead of hardcoded one and then add commented out parameters to it. You can then uncomment them before running installer.
Please submit a pull request to freeipa itself.

**Comment by adelton** [comment] 2019-11-18 10:03
Will we be able to define alternate path for `/etc/samba` that way? Or is `/etc/samba` hardcoded in the Samba code and will it always be required to be a directory?

**Comment by abbra** [comment] 2019-11-18 10:31
It is, unless you specify it with `-s /path/to/config`. However, that didn't work to @JoyceBabu.
I think what we need is what I suggested -- create base template file
```
### Added by IPA Installer ###
[global]
debug pid = yes
##[container] state directory = /data/var/lib/samba
##[container] cache directory = /data/var/lib/samba
config backend = registry
```
and switch `ADTRUSTInstance` to use it instead of a hardcoded one.

All options specified _before_ `config backend = registry` are processed normally and then switch to reading from the registry backend. It should be enough.

**Comment by JoyceBabu** [comment] 2019-11-18 12:17
> All options specified _before_ `config backend = registry` are processed normally and then switch to reading from the registry backend. It should be enough.

@abbra From what I remember, `config backend = registry` ignored all other values within `smb.conf`, even those before them.

**Comment by abbra** [comment] 2019-11-18 19:14
@JoyceBabu, I went through the code and it looks like using `include = registry` instead of `config backend = registry` would effectively be the same, only would allow to apply settings from the `smb.conf` globals that were before and after it.
What I'm worried about is that I saw some customers adding various Samba options to `smb.conf` and those options were even wrong for IPA configuration. If we would add include, these options will become active and would break existing configurations.

**Comment by adelton** [comment] 2019-11-19 15:24
@JoyceBabu, I tried to make simple
```
ipa-adtrust-install -a Secret123 --netbios-name=EXAMPLE -U
```
work in the container: https://github.com/freeipa/freeipa-container/compare/master...adelton:issue-280.

It seems that adding
```
state directory = /data/var/lib/samba
```
to `/etc/samba/smb.conf` and
```
state directory = /data/var/lib/samba
cache directory = /data/var/lib/samba
include = registry
```
to the content which is put into the generated `smb.conf` is enough to make the command pass across the OSes:
https://travis-ci.org/adelton/freeipa-container/builds/614014222

Could you please verify if the basic `ipa-adtrust-install` works for you as well with this patch?

**Comment by adelton** [comment] 2019-11-20 13:10
Related to https://github.com/freeipa/freeipa-container/issues/302, I've now locally tested that when I apply
```
diff --git a/tests/systemd-container-ipa-server-install-data.sh b/tests/systemd-container-ipa-server-install-data.sh
index 8b80cd0..85685f3 100755
--- a/tests/systemd-container-ipa-server-install-data.sh
+++ b/tests/systemd-container-ipa-server-install-data.sh
@@ -9,7 +9,7 @@ D="$2"
 docker=${docker:-docker}
 
 EXIT=false
-if ! $docker exec $C ipa-server-install -U -r EXAMPLE.TEST -p Secret123 -a Secret123 --setup-dns --no-forwarders --no-ntp ; then
+if ! $docker exec $C ipa-server-install -U -r EXAMPLE.TEST -p Secret123 -a Secret123 --setup-dns --no-forwarders --no-ntp --setup-adtrust ; then
        EXIT=true
 fi
 if ! "$EXIT" && ! $docker exec $C ipa-adtrust-install -a Secret123 --netbios-name=EXAMPLE -U ; then
```
on top of https://github.com/adelton/freeipa-container/commits/issue-280, adding `--setup-adtrust` directly to the `ipa-server-install` parameters, running `tests/run-partial-tests.sh Dockerfile.fedora-31` passes as well.

**Comment by grignix** [comment] 2019-11-20 13:47
New bug?
step
1) git clone https://github.com/freeipa/freeipa-container.git
2) cd freeipa-container
3) docker build -t freeipa-server .

Step 23/52 : RUN set -o pipefail ; patch --verbose -p0 --fuzz=0 < /root/ipa-fedora-30.patch | tee /dev/stderr | sed -n 's/^patching file //;T;/\.py$/p' | xargs python3 -m compileall
 ---> Running in b8d2aa2ddda5
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|#
|# Workaround 1364139
|#
|--- /usr/lib/python3.7/site-packages/ipaserver/install/server/replicainstall.py	2018-10-05 18:31:57.000000000 +0000
|+++ /usr/lib/python3.7/site-packages/ipaserver/install/server/replicainstall.py	2018-11-08 13:45:48.223578505 +0000
--------------------------
patching file /usr/lib/python3.7/site-packages/ipaserver/install/server/replicainstall.py
Using Plan A...
Hunk #1 FAILED at 877.
1 out of 1 hunk FAILED -- saving rejects to file /usr/lib/python3.7/site-packages/ipaserver/install/server/replicainstall.py.rej
done
The command '/bin/sh -c set -o pipefail ; patch --verbose -p0 --fuzz=0 < /root/ipa-fedora-30.patch | tee /dev/stderr | sed -n 's/^patching file //;T;/\.py$/p' | xargs python3 -m compileall' returned a non-zero code: 1

**Comment by adelton** [comment] 2019-11-20 13:55
Ah, I can reproduce it now with `--no-cache`.

Will try to prepare fix shortly.

**Comment by grignix** [comment] 2019-11-20 13:55
freeipa-server-4.8.2-1.fc31.x86_64                                            
freeipa-server-dns-4.8.2-1.fc31.noarch                                        
freeipa-server-trust-ad-4.8.2-1.fc31.x86_64

**Comment by grignix** [comment] 2019-11-20 14:13
docker build -t freeipa-server --no-cache., not helped, the errors are the same

i checked replicainstall.py on my vm fedora 31 

freeipa-server-common.noarch           4.8.1-4.fc31     
freeipa-server-dns.noarch              4.8.1-4.fc31      
freeipa-server-trust-ad.x86_64         4.8.1-4.fc31

--- replicainstall.py.orig	2019-11-20 15:38:43.606944270 +0300
+++ replicainstall.py	2019-11-20 15:39:42.505009585 +0300
@@ **-904,7 +904,7** @@
                            "certificate")
 
     installutils.verify_fqdn(config.host_name, options.no_host_dns)
-    installutils.verify_fqdn(config.master_host_name, options.no_host_dns)
+    installutils.verify_fqdn(config.master_host_name, options.no_host_dns, local_hostname=False)
 
     ccache = os.environ['KRB5CCNAME']
     kinit_keytab('host/{env.host}@{env.realm}'.format(env=api.env),

**Comment by adelton** [comment] 2019-11-20 14:23
Please `git pull` to get the latest master, https://github.com/freeipa/freeipa-container/commit/5fb8941374fadeb213d9fa4c9c8d0d8afed176a8.

**Comment by grignix** [comment] 2019-11-20 15:58
without key setup-adtrust all works, if option setup-adtrust set, an error occurs

2019-11-20T15:48:42Z DEBUG Stop of smb.service complete
2019-11-20T15:48:42Z DEBUG step duration: smb __stop 0.11 sec
2019-11-20T15:48:42Z DEBUG   [3/25]: creating samba domain object
2019-11-20T15:48:42Z DEBUG step duration: smb __create_samba_domain_object 0.02 sec
2019-11-20T15:48:42Z DEBUG   [4/25]: retrieve local idmap range
2019-11-20T15:48:42Z DEBUG raw: idrange_show('EXAMPLE.TEST_id_range', version='2.235')
2019-11-20T15:48:42Z DEBUG idrange_show('EXAMPLE.TEST_id_range', rights=False, all=False, raw=False, version='2.235')
2019-11-20T15:48:42Z DEBUG step duration: smb __retrieve_local_range 0.01 sec
2019-11-20T15:48:42Z DEBUG   [5/25]: creating samba config registry
2019-11-20T15:48:42Z DEBUG Starting external process
2019-11-20T15:48:42Z DEBUG args=['/usr/bin/net', 'conf', 'import', '/tmp/tmpqym84ijk']
2019-11-20T15:48:42Z DEBUG Process finished, return code=255
2019-11-20T15:48:42Z DEBUG stdout=
2019-11-20T15:48:42Z DEBUG stderr=Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY

2019-11-20T15:48:42Z DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ipaserver/install/service.py", line 603, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.7/site-packages/ipaserver/install/service.py", line 589, in run_step
    method()
  File "/usr/lib/python3.7/site-packages/ipaserver/install/adtrustinstance.py", line 552, in __write_smb_registry
    ipautil.run([paths.NET, "conf", "import", tmp_conf.name])
  File "/usr/lib/python3.7/site-packages/ipapython/ipautil.py", line 598, in run
    p.returncode, arg_string, output_log, error_log
ipapython.ipautil.CalledProcessError: CalledProcessError(Command ['/usr/bin/net', 'conf', 'import', '/tmp/tmpqym84ijk'] returned non-zero exit status 255: 'Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY\n')

2019-11-20T15:48:42Z DEBUG   [error] CalledProcessError: CalledProcessError(Command ['/usr/bin/net', 'conf', 'import', '/tmp/tmpqym84ijk'] returned non-zero exit status 255: 'Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY\n')
2019-11-20T15:48:42Z DEBUG   File "/usr/lib/python3.7/site-packages/ipapython/admintool.py", line 179, in execute
    return_value = self.run()
  File "/usr/lib/python3.7/site-packages/ipapython/install/cli.py", line 340, in run
    return cfgr.run()
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.7/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.7/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.7/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.7/site-packages/ipaserver/install/server/__init__.py", line 557, in main
    master_install(self)
  File "/usr/lib/python3.7/site-packages/ipaserver/install/server/install.py", line 255, in decorated
    func(installer)
  File "/usr/lib/python3.7/site-packages/ipaserver/install/server/install.py", line 932, in install
    adtrust.install(False, options, fstore, api)
  File "/usr/lib/python3.7/site-packages/ipaserver/install/adtrust.py", line 420, in install
    smb.create_instance()
  File "/usr/lib/python3.7/site-packages/ipaserver/install/adtrustinstance.py", line 899, in create_instance
    self.start_creation(show_service_name=False)
  File "/usr/lib/python3.7/site-packages/ipaserver/install/service.py", line 603, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.7/site-packages/ipaserver/install/service.py", line 589, in run_step
    method()
  File "/usr/lib/python3.7/site-packages/ipaserver/install/adtrustinstance.py", line 552, in __write_smb_registry
    ipautil.run([paths.NET, "conf", "import", tmp_conf.name])
  File "/usr/lib/python3.7/site-packages/ipapython/ipautil.py", line 598, in run
    p.returncode, arg_string, output_log, error_log

2019-11-20T15:48:42Z DEBUG The ipa-server-install command failed, exception: CalledProcessError: CalledProcessError(Command ['/usr/bin/net', 'conf', 'import', '/tmp/tmpqym84ijk'] returned non-zero exit status 255: 'Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY\n')
2019-11-20T15:48:42Z ERROR CalledProcessError(Command ['/usr/bin/net', 'conf', 'import', '/tmp/tmpqym84ijk'] returned non-zero exit status 255: 'Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY\n')

**Comment by grignix** [comment] 2019-11-20 16:02
but if manually execute
kinit admin
ipa-adtrust-install --netbios-name=IPA -a qwerty123

everything works well

**Comment by adelton** [comment] 2019-11-20 16:38
Well, for testing of the `--setup-adtrust`, you need to use the branch `issue-280` of https://github.com/adelton/freeipa-container. I have no idea why `ipa-adtrust-install` would pass when `--setup-adtrust` would not.

**Comment by grignix** [comment] 2019-11-20 21:46
I confirm through branch issue-280 it works

git clone https://github.com/adelton/freeipa-container.git && cd freeipa-container/
git checkout remotes/origin/issue-280
add --setup-adtrust  to  tests/systemd-container-ipa-server-install-data.sh 
./tests/run-partial-tests.sh Dockerfile.fedora-31
...
Done configuring CIFS.
...
OK ./tests/systemd-container-ipa-server-install-data.sh.
OK ./tests/run-partial-tests.sh.

**Comment by adelton** [comment] 2019-11-21 05:58
Good, thanks for confirming. Are you able to use the FreeIPA container from that issue-280 branch to actually establish the trust with AD and use it? I don't have Windows around to try that out ...

**Comment by grignix** [comment] 2019-11-21 15:20
For testing FreeIPA I'm currently deploying a test stand with windows  AD
I will report the results of testing

**Comment by grignix** [comment] 2019-11-22 09:02
Checked, trust works with win12r2
But I can’t add users from the FreeIPA  to AD group, AD don't see users in the IPA trust forest

[root@ipa /]# ipa trust-add --type=ad rnd.infra --admin admin --password --two-way TRUE
Active Directory domain administrator's password: 
------------------------------------------
Re-established trust to domain "rnd.infra"
------------------------------------------
  Realm name: rnd.infra
  Domain NetBIOS name: RND
  Domain Security Identifier: S-1-5-21-2600583880-2818094827-3019087222
  Trust direction: Two-way trust
  Trust type: Active Directory domain
  Trust status: Established and verified

[root@ipa /]# kinit admin@rnd.infra
Password for admin@rnd.infra: 
[root@ipa /]# klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: admin@RND.INFRA

Valid starting     Expires            Service principal
11/22/19 11:27:57  11/22/19 21:27:57  krbtgt/RND.INFRA@RND.INFRA
	renew until 11/23/19 11:27:42

**Comment by adelton** [comment] 2019-11-22 09:22
Thanks for checking the `ipa trust-add`.

As for not resolving the IPA users from AD, you might want to ask at the freeipa-users mailing list directly. The following thread from 2018 indicates that it's expected: https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/thread/BNANT26LXWEKUQCTDLCOBLD7ZGM22UZI/

**Comment by grignix** [comment] 2019-11-22 09:32
AD don't see users from IPA = it is not implemented  
https://www.freeipa.org/page/V4/Global_Catalog_Support

**Comment by pvoborni** [comment] 2019-11-22 09:41
Yes, Global Catalog is not implemented yet. But is under active development in upstream now. https://github.com/abbra/freeipa/blob/gc-wip/doc/designs/adtrust/gc-design.md

**Comment by grignix** [comment] 2019-11-22 09:57
Tell me in which branch there is support for GC?
I'm ready to be a beta tester

**Comment by adelton** [comment] 2019-11-22 10:02
The URL above suggests that it's https://github.com/abbra/freeipa/tree/gc-wip.

**Comment by abbra** [comment] 2019-11-22 11:35
@grignix it is not even in an alpha state yet. I dont' want you to waste your time right now.

**Comment by adelton** [comment] 2019-11-25 15:14
I've now created pull request https://github.com/freeipa/freeipa-container/pull/303 from my branch to have the change formally tracked, with `ipa-adtrust-install` added to test. Given that Travis CI passes for that pull request at https://travis-ci.org/freeipa/freeipa-container/builds/616657057 and @grignix reports even the `ipa trust-add` working, I'm fairly close to being convinced that I want to merge that pull request.

@JoyceBabu, @abbra, please shout if the changes in https://github.com/freeipa/freeipa-container/pull/303/files look completely wrong.

**Closed** 2019-11-26 17:56 UTC

**Comment by adelton** [comment] 2019-11-26 19:56
The tests were passing so I merged https://github.com/freeipa/freeipa-container/pull/303 to master.
