### ISSUE TITLE
RFE: include freeIPA version in docker tags

### ISSUE THREAD

**Issue by kforner** [freeipa/freeipa-container#39] opened 2015-10-29 13:41 UTC
Hi,

From what I read, it could be extremely important to deploy the same version of freeIPA, e.g. for a replica.
But imagine that you setup a master server using adelton/freeipa-server(:latest).
Then months later, you want to set up a replica, using a docker, but at that time adelton/freeipa-server has been updated and the versions do not match.

It could be very useful to include the IPA version in the tags, e.g. centos-7-ipa-441.

Best,
Karl

**Comment by adelton** [comment] 2015-10-29 15:23
I understand the request. The problem is, the images in the Docker registry are automatic builds. They get rebuilt when the underlying OS image changes or when new fixes are pushed to branches in this repository. And if in the meantime newer FreeIPA packages were pushed to the yum repositories (rebase), they will be used and will land in the updated image.

Wouldn't tagging on your end, on a machine to which you've pulled the image, or in local registry, address the use-case?

**Comment by kforner** [comment] 2015-10-29 17:49
>And if in the meantime newer FreeIPA packages were pushed to the yum repositories (rebase), they >will be used and will land in the updated image.

I do not know with other distributions, but a way to address this with debian is to use the debian snapshots repository. It is a wonderful way to build truly reproducible docker images, meaning that the image does not depend upon which day it is built.

>Wouldn't tagging on your end, on a machine to which you've pulled the image, or in local registry, address the use-case?

Yes it would, if done from the start. I hope it is not too late ! ;)

Thanks

**Comment by adelton** [comment] 2015-10-30 08:40
> I do not know with other distributions, but a way to address this with debian is to use the debian snapshots repository.

Sadly, I'm not aware of similar repositories for Fedora or CentOS. Fedora's updates receive stream of erratas and only two highest versions (releases) of the package are preserved.

And I don't have the capacity to maintain them for the purpose of this project. Is it OK to close this issue?

> >  Wouldn't tagging on your end, on a machine to which you've pulled the image, or in local registry, address the use-case?
> 
> Yes it would, thanks.

You can always find the image and export it on the machine where you run the initial master.

Also note that the images will upgrade the underlying configuration and data when newer image is run with data produced by an older image. Of course, it's good to test first on a copy of the data but if you pull newer image, remove the original container (that used the original image) and run new container from the new image and bind mount the original data (```-v /opt/ipa-data:/data:Z```), the schema, data, and configuration will get upgraded in place.

**Comment by kforner** [comment] 2015-10-30 09:13
Very good to know ! Thanks a lot.

**Comment by kforner** [comment] 2015-12-21 15:01
still, not having version tags makes you unable to reproduce errors that your users may have.
You could keep automatic builds for your branches, and explicitly push/upload images with explicit tags (like freeipa version, date...).
Then you could recommend to your users to use these explicit tags in production.

**Comment by anguslees** [comment] 2017-03-05 23:52
Unfortunately, the lack of stable version tags makes the `freeipa/freeipa-server` image only useful as a demo toy.  Can I re-request that upstream come up with some way to tag versions on release rather than ask all users to build something themselves? (perhaps by configuring dockerhub to autobuild from git branches/tags and adding such branches/tags to this github repo?)

**Comment by martbab** [comment] 2017-03-06 07:07
Versioning of the images seems to be a good idea to me. However, the problem is that we would need to devise a schema that can reflect all of the following operations:

* rebuilds due to new version of FreeIPA RPMs
* rebuilds fixing bugs/adding new features to Dockerfiles and/or helper scripts
* rebuilds which do not change FreeIPA version nor Dockerfiles, e.g. due to fixing broken/buggy dependencies

We would have to think hard and come up with something that makes sense to community and does not further confuse users.

**Comment by adelton** [comment] 2017-03-06 08:23
The `freeipa/freeipa-server` is supposed to be a rolling version across the operating systems. Unfortunately, there does not seem to be a way to get the package version in build time and put it to label or tag. And this repo is really the upstream of the containerization effort.

Of course, doing something like `dnf install "freeipa-server = 4.4.3"` in the `Dockerfile` wouldn't be hard ... but knowing when new Dockerfile with new version should be made available is. My proposal therefore be to do the version-tagged builds of the container in `fedora/` and/or `centos/` namespace, just like we do it in `rhel/` -- the maintainers of the packages in the OS know when they built new version and can act accordingly.

**Comment by Trisooma** [comment] 2017-05-14 19:10
Maybe it's an idea to at least make the version of freeipa-server explicit in the commit message.

The current version that I can pull from dockerhub (build time: 2017-03-28T19:26:53.326478373+00:00) does not work for me after restarting fresh server after installation. Probably related to #99.

Now the question I have is, what version should I revert to?
At least some info in the commit message will help me (and maybe other users as well).

Thanks

**Comment by adelton** [comment] 2017-05-15 09:02
> Maybe it's an idea to at least make the version of freeipa-server explicit in the commit message.

Commit message does not have any relationship to package versions found in the repository at the time container image is built.

> The current version that I can pull from dockerhub (build time: 2017-03-28T19:26:53.326478373+00:00) does not work for me after restarting fresh server after installation. Probably related to #99.

That issue is about `docker-compose` setup and we were never able to reproduce it.

**Comment by adelton** [comment] 2018-07-04 09:34
I'm going to close this request. We don't have a good way to maintain this. The image is written in such a way that it upgrades data where necessary when you move to newer image, the same way it happens when you upgrade packages with `dnf` or `yum` on on-host installation.

**Closed by adelton** 2018-07-04 09:34 UTC
