### ISSUE TITLE
/usr/lib/java/symkey.jar is missing in freeipa/freeipa-server

### ISSUE THREAD

**Issue by chesty** [freeipa/freeipa-container#169] opened 2017-12-02 04:47 UTC
Hi,

/usr/lib/java/symkey.jar is missing, it stops pki-tomcatd (from memory) from working,
dnf install pki-symkey fixes the problem

cheers.

**Comment by adelton** [comment] 2017-12-02 07:55
Which (base) image is this? Is this problem only present in the containers or with on-host intallations as well?

**Comment by chesty** [comment] 2017-12-02 08:12
I'm not sure what you mean by base image, would freeipa/freeipa-server be it? I think that's fedora-25 right? 
it's the docker-compose.yaml in [https://github.com/freeipa/freeipa-container/issues/135#issuecomment-348427545](https://github.com/freeipa/freeipa-container/issues/135#issuecomment-348427545) 
I've only ever played with the containers.

**Comment by stlaz** [comment] 2017-12-04 07:53
A base-image is the highest parent image in the hierarchy for some image (in case of freeipa/freeipa-server:latest it's Fedora 25 right now).
I tried reaching out to the Dogtag (PKI) team to see whether pki-symkey is really required and if so, why don't they have it in the requirements (not even on F27).

**Comment by adelton** [comment] 2017-12-04 07:58
@stlaz, what I'm baffled though, why wouldn't the issue be seen outside of containers as well?

**Comment by stlaz** [comment] 2017-12-04 08:14
@adelton Not sure. We also did not see any logs so this may not necessary be the root cause of the issue. Note that Dogtag is very memory demanding so a restart **possibly required** (I do not know for sure it needs that) by the rpm of the component could have appeared to fix the server but did not really in the longer run.

**Comment by chesty** [comment] 2017-12-04 09:29
I did think it was strange a package was missing and no one noticed. I rebuilt the container without pki-symkey and it seems to be working ok. There is a warning in the logs, but it started OK.
```
Dec 04 09:12:35 ipa.kkts.com.au server[215]: Java virtual machine used: /usr/lib/jvm/jre-1.8.0-openjdk/bin/java
Dec 04 09:12:35 ipa.kkts.com.au server[215]: classpath used: /usr/share/tomcat/bin/bootstrap.jar:/usr/share/tomcat/bin/tomcat-juli.jar:/usr/lib/java/commons-daemon.jar
Dec 04 09:12:35 ipa.kkts.com.au server[215]: main class used: org.apache.catalina.startup.Bootstrap
Dec 04 09:12:35 ipa.kkts.com.au server[215]: flags used: -DRESTEASY_LIB=/usr/share/java/resteasy -Djava.library.path=/usr/lib64/nuxwdog-jni
Dec 04 09:12:35 ipa.kkts.com.au server[215]: options used: -Dcatalina.base=/var/lib/pki/pki-tomcat -Dcatalina.home=/usr/share/tomcat -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp -Djava.util
.logging.config.file=/var/lib/pki/pki-tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager     -Djava.security.manager     -Djava.security.policy==/var/lib/pki/pki-tomc
at/conf/catalina.policy
Dec 04 09:12:35 ipa.kkts.com.au server[215]: arguments used: start
Dec 04 09:12:36 ipa.kkts.com.au server[215]: WARNING: Problem with JAR file [/usr/share/pki/server/common/lib/symkey.jar], exists: [false], canRead: [false]
```
I guess it was a coincidence that it started working after I added the package, and the fix was some other unrelated change.

**Comment by edewata** [comment] 2017-12-05 01:11
Hi, pki-symkey is only required by pki-tks and pki-tps. It's not required by pki-ca and pki-kra, so IPA should be able to run without it.

**Comment by stlaz** [comment] 2017-12-05 11:03
Thank you, @edewata.

Closing this issue as invalid, feel free to open a new one once you find the root cause of your problem

**Closed by stlaz** 2017-12-05 11:03 UTC
