### ISSUE TITLE
ipa-client-install error: "No valid Negotiate header in server response"

### ISSUE THREAD

**Issue by kzarzycki** [freeipa/freeipa-container#274] opened 2019-07-30 10:49 UTC
I'm trying to run `freeipa-container` but it fails on `ipa-client-install` section. 
I run the container with the following command:
```
docker run --rm --privileged --name freeipa-server-container -ti  -h ipa.example.test   \
 -v /sys/fs/cgroup:/sys/fs/cgroup:ro    -v /run -v /tmp    -v /dev/urandom:/dev/random:ro \
 -e PASSWORD=S23 --sysctl net.ipv6.conf.all.disable_ipv6=0  \
 freeipa/freeipa-server no-exit -U -r EXAMPLE.TEST --no-ntp
```
(I need "--privileged" "--sysctl net.ipv6.conf.all.disable_ipv6=0" and "-v /run -v /tmp" because of some other issues, that these options solved. )

The error I get is the following (extract from ipaclient-install.log) : 
```
2019-07-30T10:36:39Z DEBUG failed to find session_cookie in persistent storage for principal 'host/ipa.example.test@EXAMPLE.TEST'
2019-07-30T10:36:39Z DEBUG trying https://ipa.example.test/ipa/json
2019-07-30T10:36:39Z DEBUG Created connection context.rpcclient_139825453996184
2019-07-30T10:36:39Z DEBUG [try 1]: Forwarding 'schema' to json server 'https://ipa.example.test/ipa/json'
2019-07-30T10:36:40Z DEBUG New HTTP connection (ipa.example.test)
2019-07-30T10:36:40Z DEBUG HTTP connection destroyed (ipa.example.test)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ipaclient/remote_plugins/__init__.py", line 126, in get_package
    plugins = api._remote_plugins
AttributeError: 'API' object has no attribute '_remote_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.7/site-packages/ipalib/rpc.py", line 677, in _auth_complete
    message=u"No valid Negotiate header in server response")
ipalib.errors.KerberosError: No valid Negotiate header in server response
2019-07-30T10:36:40Z DEBUG Destroyed connection context.rpcclient_139825453996184
2019-07-30T10:36:40Z DEBUG   File "/usr/lib/python3.7/site-packages/ipapython/admintool.py", line 179, in execute
    return_value = self.run()
  File "/usr/lib/python3.7/site-packages/ipapython/install/cli.py", line 340, in run
    return cfgr.run()
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 360, in run
    return self.execute()
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 386, in execute
    for rval in self._executor():
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.7/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 655, in _configure
    next(executor)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 431, in __runner
    exc_handler(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 460, in _handle_execute_exception
    self._handle_exception(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 518, in _handle_exception
    self.__parent._handle_exception(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 515, in _handle_exception
    super(ComponentBase, self)._handle_exception(exc_info)
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 450, in _handle_exception
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 421, in __runner
    step()
  File "/usr/lib/python3.7/site-packages/ipapython/install/core.py", line 418, in <lambda>
    step = lambda: next(self.__gen)
  File "/usr/lib/python3.7/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
    six.reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
    value = gen.send(prev_value)
  File "/usr/lib/python3.7/site-packages/ipapython/install/common.py", line 65, in _install
    for unused in self._installer(self.parent):
  File "/usr/lib/python3.7/site-packages/ipaclient/install/client.py", line 3842, in main
    install(self)
  File "/usr/lib/python3.7/site-packages/ipaclient/install/client.py", line 2555, in install
    _install(options)
  File "/usr/lib/python3.7/site-packages/ipaclient/install/client.py", line 2867, in _install
    api.finalize()
  File "/usr/lib/python3.7/site-packages/ipalib/plugable.py", line 741, in finalize
    self.__do_if_not_done('load_plugins')
  File "/usr/lib/python3.7/site-packages/ipalib/plugable.py", line 429, in __do_if_not_done
    getattr(self, name)()
  File "/usr/lib/python3.7/site-packages/ipalib/plugable.py", line 621, in load_plugins
    for package in self.packages:
  File "/usr/lib/python3.7/site-packages/ipalib/__init__.py", line 949, in packages
    ipaclient.remote_plugins.get_package(self),
  File "/usr/lib/python3.7/site-packages/ipaclient/remote_plugins/__init__.py", line 134, in get_package
    plugins = schema.get_package(server_info, client)
  File "/usr/lib/python3.7/site-packages/ipaclient/remote_plugins/schema.py", line 553, in get_package
    schema = Schema(client)
  File "/usr/lib/python3.7/site-packages/ipaclient/remote_plugins/schema.py", line 402, in __init__
    fingerprint, ttl = self._fetch(client, ignore_cache=read_failed)
  File "/usr/lib/python3.7/site-packages/ipaclient/remote_plugins/schema.py", line 427, in _fetch
    schema = client.forward(u'schema', **kwargs)['result']
  File "/usr/lib/python3.7/site-packages/ipalib/rpc.py", line 1149, in forward
    return self._call_command(command, params)
  File "/usr/lib/python3.7/site-packages/ipalib/rpc.py", line 1125, in _call_command
    return command(*params)
  File "/usr/lib/python3.7/site-packages/ipalib/rpc.py", line 1279, in _call
    return self.__request(name, args)
  File "/usr/lib/python3.7/site-packages/ipalib/rpc.py", line 1246, in __request
    verbose=self.__verbose >= 3,
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.7/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.7/site-packages/ipalib/rpc.py", line 677, in _auth_complete
    message=u"No valid Negotiate header in server response")

2019-07-30T10:36:40Z DEBUG The ipa-client-install command failed, exception: KerberosError: No valid Negotiate header in server response
2019-07-30T10:36:40Z ERROR No valid Negotiate header in server response
2019-07-30T10:36:40Z ERROR The ipa-client-install command failed. See /var/log/ipaclient-install.log for more information
```

I will appreciate help in solving this issue.

**Comment by adelton** [comment] 2019-07-30 12:14
I'd focus on resolving the issues that forced you to use `--privileged`, to be able to remove it. In the past we've seen it causing more harm than help.

**Comment by adelton** [comment] 2019-08-23 13:01
Were you able to make some progress with the investigation?

**Comment by zwets** [comment] 2019-09-09 23:29
Thanks @adelton for looking into this. I run into the same **No valid Negotiate header in server response**. I'm using the image built from `Dockerfile.fedora-rawhide`, with `ipa-data-fedora-31.patch` and `ipa-fedora-30.patch` updated to refer to python 3.8.

Like @kzarzycki I need `--sysctl net.ipv6.conf.all.disable_ipv6=0` and `--privileged`. My host is Ubuntu 18.04.

Running without `--privileged` fails early in the process, due to `hostnamectl` failing. I've tried with `--security-opt seccomp=unconfined` instead, but this gives the same error result. `--privileged` with and without `--read-only=true` both get me to the point where the client install fails. 

When at that moment I `curl -D headers.txt --cacert /etc/ipa/ca.crt https://ipa.example.test/ipa/json`, the `WWW-Authenticate: Negotiate` is in `headers.txt` as expected.

**Comment by adelton** [comment] 2019-09-10 06:26
Can you open issue specific to the `hostnamectl` failure? We don't see the problem neither on RHELs/CentOSes,/Fedoras, nor in Travis CI which runs Ubuntu on the hosts, so I wonder what the issue is.

**Comment by adelton** [comment] 2019-09-10 06:28
By the way, the Fedora rawhide setup is bound to give you segfault due to https://bugzilla.redhat.com/show_bug.cgi?id=1747913, a.k.a. https://bugzilla.redhat.com/show_bug.cgi?id=1747901. Fedora 30 and CentOS 7 images are what you are looking for, really.

**Comment by adelton** [comment] 2019-09-10 06:31
By the way, can you try `tests/run-partial-tests.sh Dockerfile.fedora-30`? That's exactly how we run things in Travis CI (Ubuntu).

**Comment by zwets** [comment] 2019-09-10 09:46
> By the way, the Fedora rawhide setup is bound to give you segfault due to https://bugzilla.redhat.com/show_bug.cgi?id=1747913, a.k.a. https://bugzilla.redhat.com/show_bug.cgi?id=1747901. Fedora 30 and CentOS 7 images are what you are looking for, really.

Thanks for the heads up. I had switched to rawhide due to [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1745450), which I thought was the cause of my issue. Will go back to Fedora 30 as you suggest.

**Comment by zwets** [comment] 2019-09-10 15:56
> By the way, can you try `tests/run-partial-tests.sh Dockerfile.fedora-30`? That's exactly how we run things in Travis CI (Ubuntu).

I didn't look at the output in detail, but it ends with the lines

```
OK tests/systemd-container-ipa-server-install-data.sh.
OK tests/run-partial-tests.sh.
```

... which suggests all went well. I'll have to take a look at what the tests do differently from me.

**Comment by adelton** [comment] 2019-09-10 16:33
You are using `-v` for `/run` and `/tmp` while the tests use `--tmpfs`, and you use `-ti`.

You can play with the `$docker run` command in `tests/run-partial-tests.sh` to see if you will manage to break the test with your exact options.

**Comment by adelton** [comment] 2019-09-11 07:30
To maybe avoid confusion, the `tests/run-partial-tests.sh` actually starts systemd-based container (with FreeIPA installed) and then runs the `ipa-server-install` via `docker exec`. But if that passes, we know that configuring FreeIPA server on that container platform is possible.

To test the create-container-and-let-it-ipa-server-install-upon-the-first-invocation behaviour, use the `tests/run-master-and-replica.sh` with the name of image (so this test script does not take Dockerfile but image as parameter).

**Comment by zwets** [comment] 2019-09-11 09:40
I've found the culprit: it is having `--ip-address` in the `ipa-server-install-options`. The tests don't have it, and if I leave it out then all goes fine.

I had added this option reasoning that IPA would need to know its "public" IP address (rather than its docker-internal `172.17.0.2`), but apparently it doesn't.

FTR, these are my `ipa-server-install-options`:

```
--ds-password=***
--admin-password=***
--unattended
--domain=zwets.it
--realm=ZWETS.IT
--hostname='ipa.zwets.it'
--ssh-trust-dns
--mkhomedir
--idstart=2000
--no-ntp
```

And this is my `docker run`:

```
docker run \
    --name ipa-server \ 
    -h ipa.zwets.it \
    -v /var/lib/ipa-server:/data:Z \
    -v /var/lib/ipa-server/machine-id:/etc/machine-id:ro \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    --dns=10.103.0.24 --dns=10.103.0.23 \
    --tmpfs /run --tmpfs /tmp \
    --sysctl net.ipv6.conf.lo.disable_ipv6=0 \
    -p 10.103.0.21:80:80 -p 10.103.0.21:443:443 \
    -p 10.103.0.21:389:389 -p 10.103.0.21:636:636 \
    -p 10.103.0.21:88:88 -p 10.103.0.21:464:464 \
    -p 10.103.0.21:88:88/udp -p 10.103.0.21:464:464/udp \
    freeipa-server
```

I include the host IP address in the `-p ...` arguments because the host has multiple interfaces, and I want to tie IPA to just the DNS registered one. If you're are happy to have IPA listen on all interfaces, `-p PORT:PORT` would suffice.

**Comment by zwets** [comment] 2019-09-11 09:55
_Final thought_: this probably doesn't solve the issue for users who want IPA to provide DNS (`--setup-dns`), as they will have to provide `--ip-address`, I assume.

**Comment by adelton** [comment] 2019-09-11 11:30
If the reason for the server to know its external IP address is to properly put it to the DNS, please use the `IPA_SERVER_IP` environment variable for that.

**Comment by zwets** [comment] 2019-09-11 12:03
If this means that `--ip-address` would never make sense when installing the container (just like `--hostname` doesn't, see [the hostnamectl issue](https://github.com/freeipa/freeipa-container/issues/284)), then I suppose this issue can be closed by making this explicit in the README.

**Comment by adelton** [comment] 2019-09-11 14:03
Updated README pushed to master: https://github.com/freeipa/freeipa-container/commit/af342f3005d4a91915bf51cd6bbd44f315e1b7cc

**Comment by adelton** [comment] 2019-09-11 14:05
@zwets, so to summarize, in your case, was running the container `--privileged` the main cause of the `No valid Negotiate header in server response` issue, or was it the `--ip-address` option to `ipa-server-install`?

**Comment by zwets** [comment] 2019-09-11 19:37
No, the `--privileged` flag made no difference. It was strictly the `--ip-address` option.

As for the underlying cause, I'm not sure. I eliminated the UFW firewall by testing with it disabled, which made no difference.

*Side note*: what triggered me to check this was seeing in the journal log a number of requests from `172.17.0.2` to `10.103.0.21` on port `8080` being blocked. I am not familiar enough with UFW internals to know for sure, but it seems plausible that it would block traffic from `172.17.0.2` to `10.103.0.21.

However, no other traffic (to 88, 389, 464. 80, 443) was reported blocked _even if those ports were also closed to the `172.16/12` network_ (I had openend them to `10.103/24` only). This is likely explained by Docker creating an `iptables` route for every `-p` published port (of which `8080` isn't one), thus preempting the firewall. 

Either way, port `443` was open and accessible from `172.17.0.2` (and elsewhere). In fact, `curl` to https://ipa.zwets.it/ipa/json returned a normal response, _with_ the `WWW-Authenticate: Negotiate` header.

**Comment by kzarzycki** [comment] 2019-09-11 20:05
I'm sorry for not being up to date, but I lost this thread.
Hmm, where is the `--ip-address` option specified? I haven't used it in my call. That means probably that I have a different error (maybe caused by the `--privileged`) or I don't know where this `--ip-address` is added. 
In the meantime, I will try my best in a week to remove the `--privileged`

**Comment by zwets** [comment] 2019-09-11 21:47
> Hmm, where is the `--ip-address` option specified? 

It would be on the command line or in a file `ipa-server-install-options` in the root of the directory you mount as `/data` inside the container. I do not see any such mount?

**Comment by abbra** [comment] 2019-09-12 05:26
> No, the `--privileged` flag made no difference. It was strictly the `--ip-address` option.
> 
> As for the underlying cause, I'm not sure. I eliminated the UFW firewall by testing with it disabled, which made no difference.
> 
> _Side note_: what triggered me to check this was seeing in the journal log a number of requests from `172.17.0.2` to `10.103.0.21` on port `8080` being blocked. I am not familiar enough with UFW internals to know for sure, but it seems plausible that it would block traffic from `172.17.0.2` to `10.103.0.21`.
> 
> However, no other traffic (to 88, 389, 464. 80, 443) was reported blocked _even if those ports were also closed to the `172.16/12` network_ (I had openend them to `10.103/24` only). This is likely explained by Docker creating an `iptables` route for every `-p` published port thus preempting the firewall. Port `8080` is not one of the `-p` published ports.

There are few places in FreeIPA where we use FQDN on the system to talk back to ourselves, mostly around talking from Dogtag instance to Dogtag instance. If you have FQDN resolving to external IP, the traffic would go through the external interface.

**Comment by zwets** [comment] 2019-09-13 07:14
> Please see https://vda.li/drafts/firewall-considerations.txt, these ports are in use between CA replicas.

That is a very helpful resource. @adelton the Docker image exposes 7389, 9443-9445 which I do not see in @abbra's reference. Inversely it does not expose 749 for kadmin, and 8080 and 8443 which seem needed between replicas and (optionally) from clients for OCSP requests

**Comment by adelton** [comment] 2019-09-13 07:28
Let's keep this issue focused on the `ipa-client-install` issue during the initial `ipa-server-install` and move the port discussion to https://github.com/freeipa/freeipa-container/issues/287.

**Comment by adelton** [comment] 2019-09-20 10:10
@zwets, may I assume your setup is now fine?

@kzarzycki, were you able to find your `ipa-server-install-options` content? If you don't use `--hostname` and `--ip-address` there, does the FreeIPA server container initial setup pass for you?

**Comment by adelton** [comment] 2019-10-03 16:17
I assume the issues have been resolved.

**Closed by adelton** 2019-10-03 16:17 UTC
